import type { AllSiteLocale } from './extended-site-i18n';

export const translatedPrivacyLocales = ['ja', 'zh-Hans', 'zh-Hant', 'pt-BR', 'de', 'fr', 'es'] as const;
export type TranslatedPrivacyLocale = (typeof translatedPrivacyLocales)[number];
export const privacyAppSlugs = ['aligna', 'clipnest', 'melivra', 'meriq', 'quivra', 'segra', 'tagweaver', 'vaultxt'] as const;
export type PrivacyAppSlug = (typeof privacyAppSlugs)[number];

type AppDetails = {
  appName: string;
  updatedAt: string;
  accounts: string;
  deviceItems: string[];
  deviceNotes: string[];
  serverTitle: string;
  serverItems?: string[];
  serverBody: string;
  payment: string;
  sharing: string;
  retention: string;
  security: string;
};

type LocaleText = {
  policyTitle: string;
  applies: (app: string) => string;
  updated: string;
  intro: (app: string) => string;
  headings: [string,string,string,string,string,string,string,string];
  change: string;
  contact: string;
  nav: string;
  privacy: string;
  terms: string;
};

const shared = {
  ja: {
    policyTitle: 'プライバシーポリシー', applies: (app: string) => `本プライバシーポリシーは、ONNELLABが提供する${app}アプリに適用されます。`, updated: '最終更新日', intro: (app: string) => `${app}はプライバシーを大切にしています。本アプリは以下のとおり動作します。`,
    headings: ['1. アカウントと直接識別子','2. 端末上でアクセスまたは保存するデータ','3. サーバーへの送信','4. 支払い情報','5. 広告・分析・共有','6. 保持と削除','7. セキュリティと子どものプライバシー','8. 変更とお問い合わせ'] as [string,string,string,string,string,string,string,string],
    change: 'アプリの機能、法令、ストア要件が変更された場合、本書を更新し、最終更新日も変更します。', contact: 'プライバシーに関する質問または削除依頼：', nav: 'ナビゲーション', privacy: 'プライバシーポリシー', terms: '利用規約'
  },
  'zh-Hans': {
    policyTitle: '隐私政策', applies: (app: string) => `本隐私政策适用于 ONNELLAB 提供的 ${app} 应用。`, updated: '最后更新', intro: (app: string) => `${app} 重视你的隐私。本应用按以下方式运行。`,
    headings: ['1. 账号与直接标识信息','2. 在设备上访问或存储的数据','3. 服务器传输','4. 支付信息','5. 广告、分析与共享','6. 保留与删除','7. 安全与儿童隐私','8. 变更与联系'] as [string,string,string,string,string,string,string,string],
    change: '如果应用功能、法律要求或应用商店要求发生变化，本文件将随之更新，并修改最后更新日期。', contact: '隐私问题或删除请求：', nav: '导航', privacy: '隐私政策', terms: '使用条款'
  },
  'zh-Hant': {
    policyTitle: '隱私權政策', applies: (app: string) => `本隱私權政策適用於 ONNELLAB 提供的 ${app} 應用程式。`, updated: '最後更新', intro: (app: string) => `${app} 重視你的隱私。本應用程式依下列方式運作。`,
    headings: ['1. 帳號與直接識別資訊','2. 在裝置上存取或儲存的資料','3. 伺服器傳輸','4. 付款資訊','5. 廣告、分析與分享','6. 保留與刪除','7. 安全與兒童隱私','8. 變更與聯絡'] as [string,string,string,string,string,string,string,string],
    change: '若應用程式功能、法律要求或應用程式商店要求有所變更，本文件將同步更新，並修改最後更新日期。', contact: '隱私相關問題或刪除要求：', nav: '導覽', privacy: '隱私權政策', terms: '使用條款'
  },
  'pt-BR': {
    policyTitle: 'Política de Privacidade', applies: (app: string) => `Esta Política de Privacidade se aplica ao app ${app}, fornecido pela ONNELLAB.`, updated: 'Última atualização', intro: (app: string) => `${app} respeita a sua privacidade. O app funciona conforme descrito abaixo.`,
    headings: ['1. Contas e identificadores diretos','2. Dados acessados ou armazenados no dispositivo','3. Transmissão para servidores','4. Informações de pagamento','5. Publicidade, análise e compartilhamento','6. Retenção e exclusão','7. Segurança e privacidade de crianças','8. Alterações e contato'] as [string,string,string,string,string,string,string,string],
    change: 'Se a funcionalidade do app ou requisitos legais ou das lojas mudarem, este documento será atualizado e a data de atualização também será alterada.', contact: 'Dúvidas sobre privacidade ou solicitações de exclusão:', nav: 'Navegação', privacy: 'Política de Privacidade', terms: 'Termos'
  },
  de: {
    policyTitle: 'Datenschutzerklärung', applies: (app: string) => `Diese Datenschutzerklärung gilt für die von ONNELLAB bereitgestellte App ${app}.`, updated: 'Zuletzt aktualisiert', intro: (app: string) => `${app} respektiert deine Privatsphäre. Die App arbeitet wie nachfolgend beschrieben.`,
    headings: ['1. Konten und direkte Identifikatoren','2. Auf dem Gerät verwendete oder gespeicherte Daten','3. Serverübertragung','4. Zahlungsinformationen','5. Werbung, Analyse und Weitergabe','6. Aufbewahrung und Löschung','7. Sicherheit und Datenschutz von Kindern','8. Änderungen und Kontakt'] as [string,string,string,string,string,string,string,string],
    change: 'Wenn sich App-Funktionen oder rechtliche bzw. Store-Anforderungen ändern, wird dieses Dokument aktualisiert und das Datum angepasst.', contact: 'Datenschutzfragen oder Löschanfragen:', nav: 'Navigation', privacy: 'Datenschutzerklärung', terms: 'Nutzungsbedingungen'
  },
  fr: {
    policyTitle: 'Politique de confidentialité', applies: (app: string) => `La présente Politique de confidentialité s’applique à l’app ${app} fournie par ONNELLAB.`, updated: 'Dernière mise à jour', intro: (app: string) => `${app} respecte votre vie privée. L’app fonctionne comme décrit ci-dessous.`,
    headings: ['1. Comptes et identifiants directs','2. Données consultées ou stockées sur l’appareil','3. Transmission au serveur','4. Informations de paiement','5. Publicité, analyse et partage','6. Conservation et suppression','7. Sécurité et confidentialité des enfants','8. Modifications et contact'] as [string,string,string,string,string,string,string,string],
    change: 'Si les fonctions de l’app ou les exigences légales ou des stores évoluent, ce document sera mis à jour ainsi que sa date de dernière modification.', contact: 'Questions de confidentialité ou demandes de suppression :', nav: 'Navigation', privacy: 'Politique de confidentialité', terms: 'Conditions'
  },
  es: {
    policyTitle: 'Política de privacidad', applies: (app: string) => `Esta Política de privacidad se aplica a la app ${app}, proporcionada por ONNELLAB.`, updated: 'Última actualización', intro: (app: string) => `${app} respeta tu privacidad. La app funciona como se describe a continuación.`,
    headings: ['1. Cuentas e identificadores directos','2. Datos a los que se accede o que se almacenan en el dispositivo','3. Transmisión al servidor','4. Información de pago','5. Publicidad, analítica y uso compartido','6. Conservación y eliminación','7. Seguridad y privacidad infantil','8. Cambios y contacto'] as [string,string,string,string,string,string,string,string],
    change: 'Si cambian las funciones de la app o los requisitos legales o de las tiendas, este documento se actualizará y también cambiará la fecha de última actualización.', contact: 'Consultas de privacidad o solicitudes de eliminación:', nav: 'Navegación', privacy: 'Política de privacidad', terms: 'Términos'
  }
} satisfies Record<TranslatedPrivacyLocale, LocaleText>;

const localCommon = {
  ja: { accounts: (a:string)=>`${a}では、氏名、メールアドレス、電話番号を使った登録やサインインは必要ありません。以下で説明する任意のサーバー機能を除き、アプリの内容や利用履歴がONNELLABへ送信されることはありません。`, server:'上記のアプリ機能は、ファイル内容や利用履歴をONNELLABのサーバーへ送信しません。', payment:(a:string)=>`アプリ内購入はApple App StoreまたはGoogle Playが処理します。${a}およびONNELLABはカード番号や銀行口座情報へアクセスせず、保存もしません。ストアが提供する製品、取引、利用権情報は購入確認と復元に使用されることがあります。`, sharing:(a:string)=>`${a}は広告SDK、行動分析SDK、第三者トラッキングツールを使用しません。上記目的を除いてデータを販売または共有しません。OSの共有機能を使って利用者が別のアプリやサービスへ内容を渡した場合は、そのサービスのポリシーが適用されます。`, retention:'アプリが管理するローカルデータは、該当する削除機能またはアプリのアンインストールで削除できます。利用者が管理する元ファイルと出力ファイルは利用者の管理下に残ります。ONNELLABはアプリ内容をサーバーに保持しません。', security:(a:string)=>`ONNELLABは、送信が必要なデータに合理的な技術的・組織的保護措置を講じます。${a}は13歳未満の子どもを対象としておらず、子どもの個人情報を意図的に収集しません。` },
  'zh-Hans': { accounts:(a:string)=>`${a} 不要求使用姓名、电子邮箱或电话号码注册或登录。除下文说明的可选服务器功能外，应用内容和使用记录不会传输给 ONNELLAB。`, server:'上述应用功能不会把文件内容或使用记录传输到 ONNELLAB 服务器。', payment:(a:string)=>`应用内购买由 Apple App Store 或 Google Play 处理。${a} 和 ONNELLAB 均不会访问或保存银行卡或银行账户信息。应用商店提供的产品、交易和权益信息可能用于验证和恢复购买。`, sharing:(a:string)=>`${a} 不使用广告 SDK、行为分析 SDK 或第三方跟踪工具。除上述用途外，数据不会被出售或共享。如果用户通过操作系统的分享功能主动将内容交给其他应用或服务，则适用该服务的政策。`, retention:'应用管理的本地数据可通过相应删除功能或卸载应用移除。由用户控制的源文件和输出文件仍由用户自行管理。ONNELLAB 不会在服务器上保留应用内容。', security:(a:string)=>`ONNELLAB 对必须传输的数据采取合理的技术和组织保护措施。${a} 不面向 13 岁以下儿童，也不会故意收集儿童的个人信息。` },
  'zh-Hant': { accounts:(a:string)=>`${a} 不要求使用姓名、電子郵件或電話號碼註冊或登入。除下文說明的選用伺服器功能外，應用程式內容與使用紀錄不會傳送給 ONNELLAB。`, server:'上述應用程式功能不會將檔案內容或使用紀錄傳送到 ONNELLAB 伺服器。', payment:(a:string)=>`應用程式內購買由 Apple App Store 或 Google Play 處理。${a} 與 ONNELLAB 均不會存取或儲存信用卡或銀行帳戶資料。商店提供的產品、交易與權益資訊可能用於驗證並恢復購買。`, sharing:(a:string)=>`${a} 不使用廣告 SDK、行為分析 SDK 或第三方追蹤工具。除上述用途外，資料不會被出售或分享。若使用者透過作業系統的分享功能主動將內容交給其他應用程式或服務，則適用該服務的政策。`, retention:'應用程式管理的本機資料可透過相應刪除功能或解除安裝移除。由使用者控制的來源與輸出檔案仍由使用者自行管理。ONNELLAB 不會在伺服器上保留應用程式內容。', security:(a:string)=>`ONNELLAB 對必須傳輸的資料採取合理的技術與組織保護措施。${a} 並非針對 13 歲以下兒童，也不會刻意蒐集兒童的個人資訊。` },
  'pt-BR': { accounts:(a:string)=>`${a} não exige cadastro ou login com nome, e-mail ou telefone. Exceto pelo recurso opcional de servidor descrito abaixo, o conteúdo e o histórico de uso do app não são enviados à ONNELLAB.`, server:'As funções descritas acima não enviam conteúdo de arquivos nem histórico de uso para servidores da ONNELLAB.', payment:(a:string)=>`Compras dentro do app são processadas pela Apple App Store ou Google Play. Nem ${a} nem a ONNELLAB acessam ou armazenam dados de cartão ou conta bancária. Informações de produto, transação e licença fornecidas pela loja podem ser usadas para verificar e restaurar compras.`, sharing:(a:string)=>`${a} não usa SDKs de publicidade, análise comportamental ou rastreamento de terceiros. Os dados não são vendidos nem compartilhados fora das finalidades descritas acima. Se você enviar conteúdo a outro app ou serviço pelo compartilhamento do sistema, a política desse serviço se aplica.`, retention:'Dados locais gerenciados pelo app podem ser removidos pelos controles de exclusão aplicáveis ou ao desinstalar o app. Arquivos de origem e saída controlados por você continuam sob seu controle. A ONNELLAB não mantém conteúdo do app em seus servidores.', security:(a:string)=>`A ONNELLAB aplica medidas técnicas e organizacionais razoáveis aos dados que precisam ser transmitidos. ${a} não é direcionado a menores de 13 anos e não coleta intencionalmente informações pessoais de crianças.` },
  de: { accounts:(a:string)=>`${a} erfordert keine Registrierung oder Anmeldung mit Name, E-Mail-Adresse oder Telefonnummer. Abgesehen von einer unten beschriebenen optionalen Serverfunktion werden App-Inhalte und Nutzungsverläufe nicht an ONNELLAB übertragen.`, server:'Die oben beschriebenen App-Funktionen übertragen weder Dateiinhalte noch Nutzungsverläufe an einen ONNELLAB-Server.', payment:(a:string)=>`In-App-Käufe werden über Apple App Store oder Google Play abgewickelt. Weder ${a} noch ONNELLAB greifen auf Karten- oder Bankdaten zu oder speichern sie. Von der Store-Plattform bereitgestellte Produkt-, Transaktions- und Lizenzinformationen können zur Prüfung und Wiederherstellung von Käufen genutzt werden.`, sharing:(a:string)=>`${a} verwendet keine Werbe-SDKs, verhaltensbezogenen Analyse-SDKs oder Tracking-Werkzeuge Dritter. Daten werden außerhalb der oben beschriebenen Zwecke weder verkauft noch weitergegeben. Bei einer bewussten Weitergabe über die Teilen-Funktion des Betriebssystems gilt die Richtlinie des Zielservices.`, retention:'Von der App verwaltete lokale Daten können über die jeweiligen Löschfunktionen oder durch Deinstallation entfernt werden. Vom Nutzer kontrollierte Quell- und Ausgabedateien bleiben unter dessen Kontrolle. ONNELLAB speichert keine App-Inhalte auf seinen Servern.', security:(a:string)=>`ONNELLAB setzt angemessene technische und organisatorische Schutzmaßnahmen für Daten ein, die übertragen werden müssen. ${a} richtet sich nicht an Kinder unter 13 Jahren und sammelt wissentlich keine personenbezogenen Daten von Kindern.` },
  fr: { accounts:(a:string)=>`${a} ne demande pas d’inscription ni de connexion avec un nom, une adresse e-mail ou un numéro de téléphone. À l’exception d’une fonction serveur facultative décrite ci-dessous, le contenu et l’historique d’utilisation de l’app ne sont pas transmis à ONNELLAB.`, server:'Les fonctions décrites ci-dessus ne transmettent ni le contenu des fichiers ni l’historique d’utilisation à un serveur ONNELLAB.', payment:(a:string)=>`Les achats intégrés sont traités par l’Apple App Store ou Google Play. Ni ${a} ni ONNELLAB n’accèdent aux données de carte ou de compte bancaire et ne les stockent. Les informations de produit, de transaction et de licence fournies par la boutique peuvent servir à vérifier et restaurer les achats.`, sharing:(a:string)=>`${a} n’utilise aucun SDK publicitaire, SDK d’analyse comportementale ni outil de suivi tiers. Les données ne sont ni vendues ni partagées hors des finalités décrites ci-dessus. Si l’utilisateur transmet volontairement du contenu à une autre app ou à un autre service via le partage du système, la politique de ce service s’applique.`, retention:'Les données locales gérées par l’app peuvent être supprimées avec les commandes prévues ou en désinstallant l’app. Les fichiers source et de sortie contrôlés par l’utilisateur restent sous son contrôle. ONNELLAB ne conserve aucun contenu de l’app sur ses serveurs.', security:(a:string)=>`ONNELLAB applique des mesures techniques et organisationnelles raisonnables aux données qui doivent être transmises. ${a} ne s’adresse pas aux enfants de moins de 13 ans et ne collecte pas sciemment leurs informations personnelles.` },
  es: { accounts:(a:string)=>`${a} no exige registro ni inicio de sesión con nombre, correo electrónico o número de teléfono. Salvo por una función de servidor opcional descrita más abajo, el contenido y el historial de uso de la app no se transmiten a ONNELLAB.`, server:'Las funciones descritas anteriormente no transmiten el contenido de archivos ni el historial de uso a servidores de ONNELLAB.', payment:(a:string)=>`Las compras dentro de la app las procesa Apple App Store o Google Play. Ni ${a} ni ONNELLAB acceden a los datos de tarjetas o cuentas bancarias ni los almacenan. La información de productos, transacciones y licencia proporcionada por la tienda puede usarse para verificar y restaurar compras.`, sharing:(a:string)=>`${a} no usa SDK de publicidad, SDK de analítica de comportamiento ni herramientas de seguimiento de terceros. Los datos no se venden ni comparten fuera de las finalidades descritas. Si el usuario entrega contenido voluntariamente a otra app o servicio mediante las funciones de compartir del sistema, se aplica la política de ese servicio.`, retention:'Los datos locales gestionados por la app pueden eliminarse mediante los controles correspondientes o desinstalando la app. Los archivos de origen y salida controlados por el usuario siguen bajo su control. ONNELLAB no conserva contenido de la app en sus servidores.', security:(a:string)=>`ONNELLAB aplica medidas técnicas y organizativas razonables a los datos que deben transmitirse. ${a} no está dirigida a menores de 13 años y no recopila deliberadamente información personal de niños.` }
} as const;

const appDeviceEnglish: Record<PrivacyAppSlug, { updatedAt:string; items:string[]; notes:string[] }> = {
  aligna:{updatedAt:'2026-07-30',items:['Files and file metadata that the user explicitly selects','Rename rules, previews, app preferences, and purchase entitlement stored on the device'],notes:['Preview and rename operations occur on the device.','Selected files are not uploaded to an ONNELLAB server.','On iOS, a newly named copy may be saved instead of changing the original file directly.']},
  clipnest:{updatedAt:'2026-07-30',items:['Clipboard text accessed when the user activates the ClipNest keyboard and permits paste','Saved text snippets, pins, and app preferences stored in the app’s local database'],notes:['Clipboard access is user-initiated; ClipNest does not continuously monitor the clipboard in the background.','Saved clipboard text is not uploaded to an ONNELLAB server.']},
  melivra:{updatedAt:'2026-07-30',items:['Local audio files and their media metadata','Library entries, playback history, bookmarks, playlists, search history, AI results, and app preferences stored on the device','Purchase entitlement and AI credit balance information'],notes:['Library browsing and ordinary audio playback occur on the device without uploading the audio.','AI transcript or translation processing starts only after the user selects audio and approves the disclosed credit estimate and upload.']},
  meriq:{updatedAt:'2026-08-23',items:['Project files, imported resources, and metadata you explicitly select','Project preferences, purchase entitlement status, and local app settings'],notes:['Project, preview, export, and image content processing occurs on the device.','Selected files are not uploaded to an ONNELLAB server.','Only files you explicitly choose via the system file picker are used.']},
  quivra:{updatedAt:'2026-07-30',items:['Media files that the user explicitly selects','Converted output files and app preferences stored on the device'],notes:['Selected files are converted on the device.','Source and converted files are not uploaded to an ONNELLAB server.']},
  segra:{updatedAt:'2026-07-30',items:['Audio and image files that the user explicitly selects','Generated audio or video files and app preferences stored on the device','Purchase entitlement stored on the device'],notes:['Audio trimming and media generation occur on the device.','Selected files are not uploaded to an ONNELLAB server unless the user later shares an output through another app.']},
  tagweaver:{updatedAt:'2026-07-30',items:['MP3 files and metadata that the user explicitly selects','Artwork selected from the photo library or camera','App preferences and purchase entitlement stored on the device'],notes:['Tag editing and artwork processing occur on the device.','Selected file contents are not uploaded to an ONNELLAB server.']},
  vaultxt:{updatedAt:'2026-07-30',items:['Plain-text files that the user explicitly opens or edits','Recovery data, reading state, and app preferences stored on the device','Purchase entitlement stored on the device'],notes:['Opening, viewing, editing, search, and recovery operations occur on the device.','File contents are not uploaded to an ONNELLAB server.']}
};

const localizedDevice: Record<TranslatedPrivacyLocale, Record<PrivacyAppSlug, {items:string[];notes:string[]}>> = {
  ja:{
    aligna:{items:['利用者が明示的に選択したファイルとファイルメタデータ','端末に保存される名称変更ルール、プレビュー、アプリ設定、購入権利情報'],notes:['プレビューと名称変更は端末上で処理されます。','選択したファイルはONNELLABのサーバーへアップロードされません。','iOSでは元ファイルを直接変更せず、新しい名前のコピーを保存する場合があります。']},
    clipnest:{items:['利用者がClipNestキーボードを有効にし、ペーストを許可したときにアクセスするクリップボードのテキスト','アプリのローカルデータベースに保存されるテキスト断片、ピン、設定'],notes:['クリップボードへのアクセスは利用者の操作で開始され、バックグラウンドで継続監視しません。','保存したクリップボードのテキストはONNELLABのサーバーへアップロードされません。']},
    melivra:{items:['ローカル音声ファイルとメディアメタデータ','端末に保存されるライブラリ項目、再生履歴、ブックマーク、プレイリスト、検索履歴、AI結果、設定','購入権利とAIクレジット残高情報'],notes:['ライブラリ閲覧と通常再生は音声をアップロードせず端末上で行われます。','AI文字起こし・翻訳は、利用者が音声を選び、表示されたクレジット見積もりとアップロードを承認した場合にのみ開始します。']},
    meriq:{items:['利用者が明示的に選択したプロジェクトファイル、読み込み素材、メタデータ','プロジェクト設定、購入権利状態、端末内のアプリ設定'],notes:['プロジェクト、プレビュー、書き出し、画像処理は端末上で行われます。','選択したファイルはONNELLABのサーバーへアップロードされません。','システムのファイル選択画面で利用者が選んだファイルだけを使用します。']},
    quivra:{items:['利用者が明示的に選択したメディアファイル','端末に保存される変換後ファイルとアプリ設定'],notes:['選択したファイルは端末上で変換されます。','元ファイルと変換後ファイルはONNELLABのサーバーへアップロードされません。']},
    segra:{items:['利用者が明示的に選択した音声・画像ファイル','端末に保存される生成音声・動画ファイルとアプリ設定','端末に保存される購入権利'],notes:['音声の切り出しとメディア生成は端末上で行われます。','利用者が後から別アプリへ出力を共有しない限り、選択ファイルはONNELLABサーバーへアップロードされません。']},
    tagweaver:{items:['利用者が明示的に選択したMP3ファイルとメタデータ','写真ライブラリまたはカメラから選択したアートワーク','端末に保存されるアプリ設定と購入権利'],notes:['タグ編集とアートワーク処理は端末上で行われます。','選択したファイル内容はONNELLABのサーバーへアップロードされません。']},
    vaultxt:{items:['利用者が明示的に開く、または編集するプレーンテキストファイル','端末に保存される復元データ、閲覧状態、アプリ設定','端末に保存される購入権利'],notes:['ファイルを開く・閲覧・編集・検索・復元する処理は端末上で行われます。','ファイル内容はONNELLABのサーバーへアップロードされません。']}
  },
  'zh-Hans':{} as any,'zh-Hant':{} as any,'pt-BR':{} as any,de:{} as any,fr:{} as any,es:{} as any
};

const baseTranslations: Record<Exclude<TranslatedPrivacyLocale,'ja'>, { item: (text:string)=>string }> = {
  'zh-Hans':{item:(t)=>({
    'Files and file metadata that the user explicitly selects':'用户明确选择的文件及文件元数据','Rename rules, previews, app preferences, and purchase entitlement stored on the device':'设备上保存的重命名规则、预览、应用偏好和购买权益','Clipboard text accessed when the user activates the ClipNest keyboard and permits paste':'用户启用 ClipNest 键盘并允许粘贴时访问的剪贴板文本','Saved text snippets, pins, and app preferences stored in the app’s local database':'应用本地数据库中保存的文本片段、置顶项和偏好设置','Local audio files and their media metadata':'本地音频文件及媒体元数据','Library entries, playback history, bookmarks, playlists, search history, AI results, and app preferences stored on the device':'设备上保存的资料库条目、播放记录、书签、播放列表、搜索记录、AI 结果和应用偏好','Purchase entitlement and AI credit balance information':'购买权益和 AI 点数余额信息','Project files, imported resources, and metadata you explicitly select':'你明确选择的项目文件、导入资源和元数据','Project preferences, purchase entitlement status, and local app settings':'项目偏好、购买权益状态和本地应用设置','Media files that the user explicitly selects':'用户明确选择的媒体文件','Converted output files and app preferences stored on the device':'设备上保存的转换结果文件和应用偏好','Audio and image files that the user explicitly selects':'用户明确选择的音频和图像文件','Generated audio or video files and app preferences stored on the device':'设备上保存的生成音频或视频文件和应用偏好','Purchase entitlement stored on the device':'设备上保存的购买权益','MP3 files and metadata that the user explicitly selects':'用户明确选择的 MP3 文件和元数据','Artwork selected from the photo library or camera':'从照片图库或相机选择的封面图像','App preferences and purchase entitlement stored on the device':'设备上保存的应用偏好和购买权益','Plain-text files that the user explicitly opens or edits':'用户明确打开或编辑的纯文本文件','Recovery data, reading state, and app preferences stored on the device':'设备上保存的恢复数据、阅读状态和应用偏好'} as Record<string,string>)[t]||t},
  'zh-Hant':{item:(t)=>({
    'Files and file metadata that the user explicitly selects':'使用者明確選擇的檔案與檔案中繼資料','Rename rules, previews, app preferences, and purchase entitlement stored on the device':'裝置上儲存的重新命名規則、預覽、應用程式偏好與購買權益','Clipboard text accessed when the user activates the ClipNest keyboard and permits paste':'使用者啟用 ClipNest 鍵盤並允許貼上時存取的剪貼簿文字','Saved text snippets, pins, and app preferences stored in the app’s local database':'應用程式本機資料庫中儲存的文字片段、釘選項目與偏好設定','Local audio files and their media metadata':'本機音訊檔案及其媒體中繼資料','Library entries, playback history, bookmarks, playlists, search history, AI results, and app preferences stored on the device':'裝置上儲存的媒體庫項目、播放紀錄、書籤、播放清單、搜尋紀錄、AI 結果與應用程式偏好','Purchase entitlement and AI credit balance information':'購買權益與 AI 點數餘額資訊','Project files, imported resources, and metadata you explicitly select':'你明確選擇的專案檔案、匯入資源與中繼資料','Project preferences, purchase entitlement status, and local app settings':'專案偏好、購買權益狀態與本機應用程式設定','Media files that the user explicitly selects':'使用者明確選擇的媒體檔案','Converted output files and app preferences stored on the device':'裝置上儲存的轉換輸出檔案與應用程式偏好','Audio and image files that the user explicitly selects':'使用者明確選擇的音訊與圖片檔案','Generated audio or video files and app preferences stored on the device':'裝置上儲存的產生音訊或影片檔案與應用程式偏好','Purchase entitlement stored on the device':'裝置上儲存的購買權益','MP3 files and metadata that the user explicitly selects':'使用者明確選擇的 MP3 檔案與中繼資料','Artwork selected from the photo library or camera':'從照片圖庫或相機選擇的封面圖片','App preferences and purchase entitlement stored on the device':'裝置上儲存的應用程式偏好與購買權益','Plain-text files that the user explicitly opens or edits':'使用者明確開啟或編輯的純文字檔案','Recovery data, reading state, and app preferences stored on the device':'裝置上儲存的復原資料、閱讀狀態與應用程式偏好'} as Record<string,string>)[t]||t},
  'pt-BR':{item:(t)=>({
    'Files and file metadata that the user explicitly selects':'Arquivos e metadados escolhidos explicitamente pelo usuário','Rename rules, previews, app preferences, and purchase entitlement stored on the device':'Regras de renomeação, prévias, preferências e status da licença armazenados no dispositivo','Clipboard text accessed when the user activates the ClipNest keyboard and permits paste':'Texto da área de transferência acessado quando o usuário ativa o teclado ClipNest e permite colar','Saved text snippets, pins, and app preferences stored in the app’s local database':'Trechos salvos, itens fixados e preferências armazenados no banco local do app','Local audio files and their media metadata':'Arquivos de áudio locais e respectivos metadados','Library entries, playback history, bookmarks, playlists, search history, AI results, and app preferences stored on the device':'Biblioteca, histórico de reprodução, marcadores, playlists, histórico de busca, resultados de IA e preferências armazenados no dispositivo','Purchase entitlement and AI credit balance information':'Informações de status da licença e saldo de créditos de IA','Project files, imported resources, and metadata you explicitly select':'Arquivos de projeto, recursos importados e metadados escolhidos explicitamente','Project preferences, purchase entitlement status, and local app settings':'Preferências do projeto, status de compra e configurações locais','Media files that the user explicitly selects':'Arquivos de mídia escolhidos explicitamente pelo usuário','Converted output files and app preferences stored on the device':'Arquivos convertidos e preferências armazenados no dispositivo','Audio and image files that the user explicitly selects':'Arquivos de áudio e imagem escolhidos explicitamente','Generated audio or video files and app preferences stored on the device':'Arquivos de áudio ou vídeo gerados e preferências armazenados no dispositivo','Purchase entitlement stored on the device':'Status da licença armazenado no dispositivo','MP3 files and metadata that the user explicitly selects':'Arquivos MP3 e metadados escolhidos explicitamente','Artwork selected from the photo library or camera':'Capa escolhida na fototeca ou câmera','App preferences and purchase entitlement stored on the device':'Preferências e status da licença armazenados no dispositivo','Plain-text files that the user explicitly opens or edits':'Arquivos de texto simples que o usuário abre ou edita explicitamente','Recovery data, reading state, and app preferences stored on the device':'Dados de recuperação, estado de leitura e preferências armazenados no dispositivo'} as Record<string,string>)[t]||t},
  de:{item:(t)=>({
    'Files and file metadata that the user explicitly selects':'Vom Nutzer ausdrücklich ausgewählte Dateien und Dateimetadaten','Rename rules, previews, app preferences, and purchase entitlement stored on the device':'Auf dem Gerät gespeicherte Umbenennungsregeln, Vorschauen, App-Einstellungen und Lizenzstatus','Clipboard text accessed when the user activates the ClipNest keyboard and permits paste':'Zwischenablagetext, auf den beim Aktivieren der ClipNest-Tastatur und erlaubtem Einfügen zugegriffen wird','Saved text snippets, pins, and app preferences stored in the app’s local database':'Gespeicherte Textbausteine, angeheftete Einträge und Einstellungen in der lokalen App-Datenbank','Local audio files and their media metadata':'Lokale Audiodateien und zugehörige Medienmetadaten','Library entries, playback history, bookmarks, playlists, search history, AI results, and app preferences stored on the device':'Bibliothekseinträge, Wiedergabeverlauf, Lesezeichen, Playlists, Suchverlauf, KI-Ergebnisse und App-Einstellungen auf dem Gerät','Purchase entitlement and AI credit balance information':'Lizenzstatus und KI-Guthaben','Project files, imported resources, and metadata you explicitly select':'Ausdrücklich ausgewählte Projektdateien, importierte Ressourcen und Metadaten','Project preferences, purchase entitlement status, and local app settings':'Projekteinstellungen, Kaufstatus und lokale App-Einstellungen','Media files that the user explicitly selects':'Vom Nutzer ausdrücklich ausgewählte Mediendateien','Converted output files and app preferences stored on the device':'Konvertierte Ausgabedateien und App-Einstellungen auf dem Gerät','Audio and image files that the user explicitly selects':'Ausdrücklich ausgewählte Audio- und Bilddateien','Generated audio or video files and app preferences stored on the device':'Erzeugte Audio-/Videodateien und App-Einstellungen auf dem Gerät','Purchase entitlement stored on the device':'Auf dem Gerät gespeicherte Lizenzstatus','MP3 files and metadata that the user explicitly selects':'Ausdrücklich ausgewählte MP3-Dateien und Metadaten','Artwork selected from the photo library or camera':'Aus Fotomediathek oder Kamera gewähltes Artwork','App preferences and purchase entitlement stored on the device':'App-Einstellungen und Lizenzstatus auf dem Gerät','Plain-text files that the user explicitly opens or edits':'Ausdrücklich geöffnete oder bearbeitete Klartextdateien','Recovery data, reading state, and app preferences stored on the device':'Wiederherstellungsdaten, Lesestatus und App-Einstellungen auf dem Gerät'} as Record<string,string>)[t]||t},
  fr:{item:(t)=>({
    'Files and file metadata that the user explicitly selects':'Fichiers et métadonnées explicitement sélectionnés par l’utilisateur','Rename rules, previews, app preferences, and purchase entitlement stored on the device':'Règles de renommage, aperçus, préférences et état de la licence stockés sur l’appareil','Clipboard text accessed when the user activates the ClipNest keyboard and permits paste':'Texte du presse-papiers consulté lorsque l’utilisateur active le clavier ClipNest et autorise le collage','Saved text snippets, pins, and app preferences stored in the app’s local database':'Extraits enregistrés, éléments épinglés et préférences dans la base locale de l’app','Local audio files and their media metadata':'Fichiers audio locaux et métadonnées multimédia','Library entries, playback history, bookmarks, playlists, search history, AI results, and app preferences stored on the device':'Bibliothèque, historique de lecture, signets, playlists, historique de recherche, résultats IA et préférences stockés sur l’appareil','Purchase entitlement and AI credit balance information':'Informations de état de la licence et de solde de crédits IA','Project files, imported resources, and metadata you explicitly select':'Fichiers de projet, ressources importées et métadonnées explicitement sélectionnés','Project preferences, purchase entitlement status, and local app settings':'Préférences du projet, état du état de la licence et réglages locaux','Media files that the user explicitly selects':'Fichiers multimédias explicitement sélectionnés','Converted output files and app preferences stored on the device':'Fichiers convertis et préférences stockés sur l’appareil','Audio and image files that the user explicitly selects':'Fichiers audio et image explicitement sélectionnés','Generated audio or video files and app preferences stored on the device':'Fichiers audio/vidéo générés et préférences stockés sur l’appareil','Purchase entitlement stored on the device':'État de la licence stocké sur l’appareil','MP3 files and metadata that the user explicitly selects':'Fichiers MP3 et métadonnées explicitement sélectionnés','Artwork selected from the photo library or camera':'Illustration choisie dans la photothèque ou l’appareil photo','App preferences and purchase entitlement stored on the device':'Préférences et état de la licence stockés sur l’appareil','Plain-text files that the user explicitly opens or edits':'Fichiers texte brut explicitement ouverts ou modifiés','Recovery data, reading state, and app preferences stored on the device':'Données de récupération, état de lecture et préférences stockés sur l’appareil'} as Record<string,string>)[t]||t},
  es:{item:(t)=>({
    'Files and file metadata that the user explicitly selects':'Archivos y metadatos seleccionados expresamente por el usuario','Rename rules, previews, app preferences, and purchase entitlement stored on the device':'Reglas de renombrado, vistas previas, preferencias y estado de la licencia almacenados en el dispositivo','Clipboard text accessed when the user activates the ClipNest keyboard and permits paste':'Texto del portapapeles al que se accede cuando el usuario activa el teclado ClipNest y permite pegar','Saved text snippets, pins, and app preferences stored in the app’s local database':'Fragmentos guardados, elementos fijados y preferencias almacenados en la base local de la app','Local audio files and their media metadata':'Archivos de audio locales y sus metadatos','Library entries, playback history, bookmarks, playlists, search history, AI results, and app preferences stored on the device':'Biblioteca, historial de reproducción, marcadores, listas, historial de búsqueda, resultados de IA y preferencias almacenados en el dispositivo','Purchase entitlement and AI credit balance information':'Información del estado de la licencia y saldo de créditos de IA','Project files, imported resources, and metadata you explicitly select':'Archivos de proyecto, recursos importados y metadatos seleccionados expresamente','Project preferences, purchase entitlement status, and local app settings':'Preferencias del proyecto, estado del estado de la licencia y ajustes locales','Media files that the user explicitly selects':'Archivos multimedia seleccionados expresamente','Converted output files and app preferences stored on the device':'Archivos convertidos y preferencias almacenados en el dispositivo','Audio and image files that the user explicitly selects':'Archivos de audio e imagen seleccionados expresamente','Generated audio or video files and app preferences stored on the device':'Archivos de audio o vídeo generados y preferencias almacenados en el dispositivo','Purchase entitlement stored on the device':'Estado de la licencia almacenado en el dispositivo','MP3 files and metadata that the user explicitly selects':'Archivos MP3 y metadatos seleccionados expresamente','Artwork selected from the photo library or camera':'Carátula seleccionada de la fototeca o la cámara','App preferences and purchase entitlement stored on the device':'Preferencias y estado de la licencia almacenados en el dispositivo','Plain-text files that the user explicitly opens or edits':'Archivos de texto plano que el usuario abre o edita expresamente','Recovery data, reading state, and app preferences stored on the device':'Datos de recuperación, estado de lectura y preferencias almacenados en el dispositivo'} as Record<string,string>)[t]||t}
};

const noteTranslations: Record<Exclude<TranslatedPrivacyLocale,'ja'>, { notes: (slug:PrivacyAppSlug)=>string[] }> = {
  'zh-Hans':{notes:(s)=>({aligna:['预览和重命名操作在设备上完成。','选中的文件不会上传至 ONNELLAB 服务器。','在 iOS 上，可能会保存一份使用新名称的副本，而不是直接修改原文件。'],clipnest:['剪贴板访问由用户主动触发；ClipNest 不会在后台持续监控剪贴板。','保存的剪贴板文本不会上传至 ONNELLAB 服务器。'],melivra:['资料库浏览和普通音频播放都在设备上进行，不会上传音频。','只有在用户选择音频并同意显示的点数预估和上传后，AI 转录或翻译才会开始。'],meriq:['项目、预览、导出和图像内容处理都在设备上完成。','选中的文件不会上传至 ONNELLAB 服务器。','只使用你通过系统文件选择器明确选择的文件。'],quivra:['选中的文件在设备上转换。','源文件和转换后的文件都不会上传至 ONNELLAB 服务器。'],segra:['音频裁剪和媒体生成都在设备上完成。','除非用户之后主动通过其他应用分享输出，否则选中的文件不会上传至 ONNELLAB 服务器。'],tagweaver:['标签编辑和封面处理都在设备上完成。','选中的文件内容不会上传至 ONNELLAB 服务器。'],vaultxt:['打开、查看、编辑、搜索和恢复都在设备上完成。','文件内容不会上传至 ONNELLAB 服务器。']} as Record<PrivacyAppSlug,string[]>)[s]},
  'zh-Hant':{notes:(s)=>({aligna:['預覽與重新命名操作在裝置上完成。','選取的檔案不會上傳至 ONNELLAB 伺服器。','在 iOS 上，可能會儲存一份使用新名稱的副本，而不是直接修改原始檔案。'],clipnest:['剪貼簿存取由使用者主動觸發；ClipNest 不會在背景持續監看剪貼簿。','儲存的剪貼簿文字不會上傳至 ONNELLAB 伺服器。'],melivra:['媒體庫瀏覽與一般音訊播放都在裝置上進行，不會上傳音訊。','只有在使用者選擇音訊並同意顯示的點數估算與上傳後，AI 轉錄或翻譯才會開始。'],meriq:['專案、預覽、匯出與圖片內容處理都在裝置上完成。','選取的檔案不會上傳至 ONNELLAB 伺服器。','只使用你透過系統檔案選擇器明確選擇的檔案。'],quivra:['選取的檔案在裝置上轉換。','來源與轉換後檔案都不會上傳至 ONNELLAB 伺服器。'],segra:['音訊裁切與媒體產生都在裝置上完成。','除非使用者之後主動透過其他應用程式分享輸出，否則選取檔案不會上傳至 ONNELLAB 伺服器。'],tagweaver:['標籤編輯與封面處理都在裝置上完成。','選取的檔案內容不會上傳至 ONNELLAB 伺服器。'],vaultxt:['開啟、檢視、編輯、搜尋與復原都在裝置上完成。','檔案內容不會上傳至 ONNELLAB 伺服器。']} as Record<PrivacyAppSlug,string[]>)[s]},
  'pt-BR':{notes:(s)=>({aligna:['Prévia e renomeação ocorrem no dispositivo.','Os arquivos escolhidos não são enviados a servidores da ONNELLAB.','No iOS, uma nova cópia com outro nome pode ser salva em vez de alterar diretamente o original.'],clipnest:['O acesso à área de transferência é iniciado pelo usuário; ClipNest não a monitora continuamente em segundo plano.','O texto salvo não é enviado a servidores da ONNELLAB.'],melivra:['A biblioteca e a reprodução normal funcionam no dispositivo sem enviar o áudio.','Transcrição ou tradução por IA só começa depois que o usuário escolhe o áudio e aprova a estimativa de créditos e o envio informados.'],meriq:['Projeto, prévia, exportação e processamento de imagem ocorrem no dispositivo.','Os arquivos escolhidos não são enviados a servidores da ONNELLAB.','Somente arquivos escolhidos explicitamente no seletor do sistema são usados.'],quivra:['Os arquivos escolhidos são convertidos no dispositivo.','Arquivos de origem e convertidos não são enviados a servidores da ONNELLAB.'],segra:['Corte de áudio e geração de mídia ocorrem no dispositivo.','Os arquivos escolhidos não são enviados à ONNELLAB, a menos que o usuário compartilhe depois um resultado com outro app.'],tagweaver:['Edição de tags e processamento de capas ocorrem no dispositivo.','O conteúdo dos arquivos escolhidos não é enviado à ONNELLAB.'],vaultxt:['Abertura, leitura, edição, busca e recuperação ocorrem no dispositivo.','O conteúdo dos arquivos não é enviado à ONNELLAB.']} as Record<PrivacyAppSlug,string[]>)[s]},
  de:{notes:(s)=>({aligna:['Vorschau und Umbenennung erfolgen auf dem Gerät.','Ausgewählte Dateien werden nicht auf ONNELLAB-Server hochgeladen.','Unter iOS kann eine neu benannte Kopie gespeichert werden, statt die Originaldatei direkt zu ändern.'],clipnest:['Der Zugriff auf die Zwischenablage wird vom Nutzer ausgelöst; ClipNest überwacht sie nicht dauerhaft im Hintergrund.','Gespeicherter Zwischenablagetext wird nicht auf ONNELLAB-Server hochgeladen.'],melivra:['Bibliotheksnavigation und normale Audiowiedergabe laufen auf dem Gerät ohne Audio-Upload.','KI-Transkription oder -Übersetzung startet erst nach Auswahl der Audiodatei und Bestätigung der angezeigten Guthabenschätzung und des Uploads.'],meriq:['Projekt-, Vorschau-, Export- und Bildverarbeitung erfolgt auf dem Gerät.','Ausgewählte Dateien werden nicht auf ONNELLAB-Server hochgeladen.','Verwendet werden nur Dateien, die ausdrücklich über den System-Dateiauswahldialog gewählt wurden.'],quivra:['Ausgewählte Dateien werden auf dem Gerät konvertiert.','Quell- und Ausgabedateien werden nicht auf ONNELLAB-Server hochgeladen.'],segra:['Audiozuschnitt und Medienerzeugung erfolgen auf dem Gerät.','Ausgewählte Dateien werden nicht auf ONNELLAB-Server hochgeladen, es sei denn, der Nutzer teilt später eine Ausgabe über eine andere App.'],tagweaver:['Tag-Bearbeitung und Artwork-Verarbeitung erfolgen auf dem Gerät.','Ausgewählte Dateiinhalte werden nicht auf ONNELLAB-Server hochgeladen.'],vaultxt:['Öffnen, Anzeigen, Bearbeiten, Suchen und Wiederherstellen erfolgen auf dem Gerät.','Dateiinhalte werden nicht auf ONNELLAB-Server hochgeladen.']} as Record<PrivacyAppSlug,string[]>)[s]},
  fr:{notes:(s)=>({aligna:['L’aperçu et le renommage ont lieu sur l’appareil.','Les fichiers choisis ne sont pas envoyés à un serveur ONNELLAB.','Sur iOS, une nouvelle copie renommée peut être enregistrée au lieu de modifier directement l’original.'],clipnest:['L’accès au presse-papiers est déclenché par l’utilisateur ; ClipNest ne le surveille pas en permanence en arrière-plan.','Le texte enregistré n’est pas envoyé à un serveur ONNELLAB.'],melivra:['La navigation dans la bibliothèque et la lecture audio normale se font sur l’appareil sans envoyer l’audio.','La transcription ou traduction IA ne démarre qu’après choix de l’audio et validation de l’estimation de crédits et de l’envoi annoncés.'],meriq:['Projet, aperçu, export et traitement d’image se font sur l’appareil.','Les fichiers choisis ne sont pas envoyés à un serveur ONNELLAB.','Seuls les fichiers explicitement choisis dans le sélecteur système sont utilisés.'],quivra:['Les fichiers choisis sont convertis sur l’appareil.','Les fichiers source et convertis ne sont pas envoyés à un serveur ONNELLAB.'],segra:['Le découpage audio et la génération de médias se font sur l’appareil.','Les fichiers choisis ne sont pas envoyés à ONNELLAB sauf si l’utilisateur partage ensuite une sortie avec une autre app.'],tagweaver:['La modification des tags et le traitement des illustrations se font sur l’appareil.','Le contenu des fichiers choisis n’est pas envoyé à un serveur ONNELLAB.'],vaultxt:['Ouverture, lecture, modification, recherche et récupération se font sur l’appareil.','Le contenu des fichiers n’est pas envoyé à un serveur ONNELLAB.']} as Record<PrivacyAppSlug,string[]>)[s]},
  es:{notes:(s)=>({aligna:['La vista previa y el renombrado se realizan en el dispositivo.','Los archivos seleccionados no se suben a servidores de ONNELLAB.','En iOS puede guardarse una copia con el nombre nuevo en vez de modificar directamente el original.'],clipnest:['El acceso al portapapeles lo inicia el usuario; ClipNest no lo supervisa continuamente en segundo plano.','El texto guardado no se sube a servidores de ONNELLAB.'],melivra:['La navegación por la biblioteca y la reproducción normal se realizan en el dispositivo sin subir el audio.','La transcripción o traducción con IA solo empieza después de elegir el audio y aprobar la estimación de créditos y la subida indicadas.'],meriq:['Proyecto, vista previa, exportación y procesamiento de imágenes se realizan en el dispositivo.','Los archivos seleccionados no se suben a servidores de ONNELLAB.','Solo se usan archivos que eliges expresamente en el selector del sistema.'],quivra:['Los archivos seleccionados se convierten en el dispositivo.','Los archivos de origen y convertidos no se suben a servidores de ONNELLAB.'],segra:['El recorte de audio y la generación multimedia se realizan en el dispositivo.','Los archivos seleccionados no se suben a ONNELLAB salvo que el usuario comparta después un resultado con otra app.'],tagweaver:['La edición de etiquetas y el procesamiento de carátulas se realizan en el dispositivo.','El contenido de los archivos seleccionados no se sube a servidores de ONNELLAB.'],vaultxt:['Abrir, ver, editar, buscar y recuperar se realiza en el dispositivo.','El contenido de los archivos no se sube a servidores de ONNELLAB.']} as Record<PrivacyAppSlug,string[]>)[s]}
};

for (const locale of translatedPrivacyLocales) {
  if (locale === 'ja') continue;
  for (const slug of privacyAppSlugs) {
    localizedDevice[locale][slug] = {
      items: appDeviceEnglish[slug].items.map((item) => baseTranslations[locale].item(item)),
      notes: noteTranslations[locale].notes(slug)
    };
  }
}

const melivraServer: Record<TranslatedPrivacyLocale, {items:string[];body:string;retention:string}> = {
  ja:{items:['サーバーが発行する匿名の主体識別子','承認されたAI処理に使う選択済み音声ファイル','AIクレジット購入確認に使うストア製品・取引識別子','AI処理状態、クレジット台帳、文字起こし、翻訳、生成結果のメタデータ'],body:'これらのデータは、購入確認、AIクレジット残高の維持、依頼された文字起こし・翻訳の処理と返却、重複付与の防止、運用サポートのためにのみ使用されます。',retention:'アップロードされた元音声は結果生成後に長期間保持しません。処理、結果、取引確認、クレジット台帳の記録は、サービス提供、重複決済防止、会計、紛争対応、法的義務のため保持される場合があります。削除に関する質問や依頼は下記連絡先へ送れます。'},
  'zh-Hans':{items:['服务器签发的匿名主体标识符','经批准的 AI 任务所选择的音频文件','用于验证 AI 点数购买的商店产品和交易标识符','AI 任务状态、点数账本、转录、翻译和生成结果元数据'],body:'这些数据仅用于验证购买、维护 AI 点数余额、处理并返回请求的转录或翻译、防止重复发放以及提供运营支持。',retention:'上传的源音频不会在结果生成后长期保留。任务、结果、交易验证和点数账本记录可能因服务交付、防止重复付款、会计、争议处理和法律义务而保留。删除相关问题或请求可发送至下方联系地址。'},
  'zh-Hant':{items:['伺服器簽發的匿名主體識別碼','經核准的 AI 工作所選取的音訊檔案','用於驗證 AI 點數購買的商店產品與交易識別碼','AI 工作狀態、點數帳本、轉錄、翻譯與產生結果中繼資料'],body:'這些資料僅用於驗證購買、維護 AI 點數餘額、處理並回傳要求的轉錄或翻譯、防止重複發放，以及提供營運支援。',retention:'上傳的來源音訊不會在結果產生後長期保留。工作、結果、交易驗證與點數帳本紀錄可能因服務提供、防止重複付款、會計、爭議處理與法律義務而保留。刪除相關問題或要求可寄至下方聯絡地址。'},
  'pt-BR':{items:['Identificador anônimo emitido pelo servidor','Arquivo de áudio selecionado para uma tarefa de IA aprovada','Identificadores de produto e transação da loja usados para verificar compras de créditos de IA','Status da tarefa de IA, registros do saldo, transcrições, traduções e metadados de resultados gerados'],body:'Esses dados são usados somente para verificar compras, manter o saldo de créditos de IA, processar e devolver a transcrição ou tradução solicitada, evitar concessões duplicadas e prestar suporte operacional.',retention:'O áudio de origem enviado não é mantido por longo prazo após a geração do resultado. Registros de tarefas, resultados, verificação de transações e saldo podem ser mantidos para prestação do serviço, prevenção de pagamentos duplicados, contabilidade, disputas e obrigações legais. Dúvidas ou solicitações de exclusão podem ser enviadas ao contato abaixo.'},
  de:{items:['Anonyme, vom Server vergebene Benutzerkennung','Ausgewählte Audiodatei für einen bestätigten KI-Auftrag','Store-Produkt- und Transaktionskennungen zur Prüfung von KI-Guthabenkäufen','KI-Auftragsstatus, Guthabenbuchungen, Transkripte, Übersetzungen und Metadaten erzeugter Ergebnisse'],body:'Diese Daten werden ausschließlich zur Kaufprüfung, Verwaltung des KI-Guthabens, Verarbeitung und Rückgabe der angeforderten Transkription oder Übersetzung, Vermeidung doppelter Gutschriften und für betrieblichen Support verwendet.',retention:'Hochgeladenes Quell-Audio wird nach der Ergebniserstellung nicht langfristig gespeichert. Auftrags-, Ergebnis-, Transaktionsprüfungs- und Guthabenaufzeichnungen können für Leistungserbringung, Vermeidung doppelter Zahlungen, Buchhaltung, Streitfälle und gesetzliche Pflichten aufbewahrt werden. Löschanfragen können an die unten genannte Kontaktadresse gesendet werden.'},
  fr:{items:['Identifiant anonyme attribué par le serveur','Fichier audio choisi pour une tâche IA approuvée','Identifiants de produit et de transaction du store utilisés pour vérifier les achats de crédits IA','État des tâches IA, registre de crédits, transcriptions, traductions et métadonnées des résultats générés'],body:'Ces données servent uniquement à vérifier les achats, maintenir le solde de crédits IA, traiter et renvoyer la transcription ou traduction demandée, éviter les crédits en double et assurer le support opérationnel.',retention:'L’audio source envoyé n’est pas conservé à long terme après la génération du résultat. Les enregistrements de tâches, résultats, vérifications de transaction et crédits peuvent être conservés pour la fourniture du service, la prévention des paiements en double, la comptabilité, les litiges et les obligations légales. Les demandes de suppression peuvent être envoyées à l’adresse ci-dessous.'},
  es:{items:['Identificador anónimo emitido por el servidor','Archivo de audio seleccionado para un trabajo de IA aprobado','Identificadores de producto y transacción de la tienda usados para verificar compras de créditos de IA','Estado de tareas de IA, registro de créditos, transcripciones, traducciones y metadatos de resultados generados'],body:'Estos datos se usan únicamente para verificar compras, mantener el saldo de créditos de IA, procesar y devolver la transcripción o traducción solicitada, evitar concesiones duplicadas y prestar soporte operativo.',retention:'El audio de origen subido no se conserva a largo plazo después de generar el resultado. Los registros de tareas, resultados, verificación de transacciones y créditos pueden conservarse para prestar el servicio, evitar pagos duplicados, contabilidad, gestión de disputas y obligaciones legales. Las solicitudes de eliminación pueden enviarse al contacto indicado abajo.'}
};

export function getAppPrivacyCopy(slug: PrivacyAppSlug, locale: TranslatedPrivacyLocale): { localeText: LocaleText; details: AppDetails } {
  const appName = {aligna:'Aligna',clipnest:'ClipNest',melivra:'Melivra',meriq:'Meriq',quivra:'Quivra',segra:'Segra',tagweaver:'TagWeaver',vaultxt:'VaultXT'}[slug];
  const common = localCommon[locale];
  const device = localizedDevice[locale][slug];
  const melivra = slug === 'melivra' ? melivraServer[locale] : undefined;
  const meriqAccounts = {
    ja:'Meriqでは、氏名、メールアドレス、電話番号を使った登録やサインインは必要ありません。','zh-Hans':'Meriq 不要求使用姓名、电子邮箱或电话号码注册或登录。','zh-Hant':'Meriq 不要求使用姓名、電子郵件或電話號碼註冊或登入。','pt-BR':'Meriq não exige cadastro ou login com nome, e-mail ou telefone.',de:'Meriq erfordert keine Registrierung oder Anmeldung mit Name, E-Mail-Adresse oder Telefonnummer.',fr:'Meriq ne demande pas d’inscription ni de connexion avec un nom, une adresse e-mail ou un numéro de téléphone.',es:'Meriq no exige registro ni inicio de sesión con nombre, correo electrónico o número de teléfono.'
  } as Record<TranslatedPrivacyLocale,string>;
  const meriqServer = {
    ja:'アプリ内容（プロジェクト、画像、利用データ）はONNELLABのサーバーへ送信されません。診断ログにもファイル内容は含まれません。','zh-Hans':'应用内容（项目、图像、使用数据）不会发送至 ONNELLAB 服务器。诊断日志不包含文件内容。','zh-Hant':'應用程式內容（專案、圖片、使用資料）不會傳送至 ONNELLAB 伺服器。診斷記錄不包含檔案內容。','pt-BR':'O conteúdo do app (projetos, imagens e dados de uso) não é enviado aos servidores da ONNELLAB. Logs de diagnóstico não incluem o conteúdo dos arquivos.',de:'App-Inhalte (Projekte, Bilder, Nutzungsdaten) werden nicht an ONNELLAB-Server gesendet. Diagnoseprotokolle enthalten keine Dateiinhalte.',fr:'Le contenu de l’app (projets, images, données d’utilisation) n’est pas envoyé aux serveurs ONNELLAB. Les journaux de diagnostic ne contiennent pas le contenu des fichiers.',es:'El contenido de la app (proyectos, imágenes y datos de uso) no se envía a servidores de ONNELLAB. Los registros de diagnóstico no incluyen el contenido de los archivos.'
  } as Record<TranslatedPrivacyLocale,string>;
  return {
    localeText: shared[locale],
    details: {
      appName, updatedAt: appDeviceEnglish[slug].updatedAt,
      accounts: slug === 'meriq' ? meriqAccounts[locale] : common.accounts(appName),
      deviceItems: device.items, deviceNotes: device.notes,
      serverTitle: shared[locale].headings[2], serverItems: melivra?.items,
      serverBody: slug === 'melivra' ? melivra!.body : slug === 'meriq' ? meriqServer[locale] : common.server,
      payment: common.payment(appName), sharing: common.sharing(appName),
      retention: slug === 'melivra' ? melivra!.retention : common.retention,
      security: common.security(appName)
    }
  };
}
