import type { ExtendedSiteLocale } from './extended-site-i18n';

export type ExtendedProductCopy = {
  subtitle: string;
  body: string;
  faqTitle: string;
  faq: Array<{ question: string; answer: string }>;
};

const make = (subtitle: string, body: string, faqTitle: string, faq: ExtendedProductCopy['faq']): ExtendedProductCopy => ({ subtitle, body, faqTitle, faq });

export const extendedProductCopy: Record<ExtendedSiteLocale, Record<string, ExtendedProductCopy>> = {
  'pt-BR': {
    aligna: make('Renomeador de arquivos em lote', `Aligna renomeia vários arquivos de uma vez usando regras claras e previsíveis.\n\nUse os mesmos padrões em fotos, músicas e documentos: adicione datas ou números sequenciais, troque espaços por sublinhados, remova caracteres inválidos e crie nomes de arquivos de música a partir das tags.\n\n## Principais recursos\n\n- Adicionar data ou numeração sequencial\n- Trocar espaços por sublinhados\n- Remover caracteres inválidos\n- Organizar fotos pela data de captura\n- Criar nomes a partir de artista, número da faixa e título\n- Conferir uma prévia antes de aplicar\n\nAligna não é um gerenciador de arquivos nem um serviço em nuvem. Não exige conta, não tem anúncios e faz o processamento no dispositivo. No iOS, por limitações do sistema, o arquivo pode ser salvo como uma nova cópia com outro nome em vez de renomear o original diretamente.`, 'Perguntas frequentes', [
      { question: 'O nome do arquivo original é alterado diretamente?', answer: 'No Android, arquivos selecionados podem ser renomeados. No iOS, por limitações do sistema, o resultado é salvo como um novo arquivo com o novo nome.' },
      { question: 'Posso conferir os novos nomes antes de aplicar?', answer: 'Sim. A prévia mostra os nomes resultantes antes de qualquer alteração.' },
      { question: 'Meus arquivos são enviados para um servidor?', answer: 'Não. O processamento é local e não exige conta nem armazenamento em nuvem.' }
    ]),
    clipnest: make('Área de transferência e textos reutilizáveis', `ClipNest é uma ferramenta local de área de transferência para iPhone e iPad.\n\nQuando o teclado ClipNest é aberto, ele verifica a área de transferência naquele momento e salva novos textos no dispositivo. Assim você pode reutilizar mensagens, endereços, e-mails, links e trechos frequentes sem procurar novamente em outros apps ou notas.\n\n## Principais recursos\n\n- Salvar o texto copiado ao abrir o teclado\n- Colar diretamente pelo teclado\n- Fixar itens usados com frequência\n- Reutilizar o histórico recente\n- Tratar entradas duplicadas\n- Armazenamento local no dispositivo\n\nClipNest não monitora a área de transferência continuamente. Os textos salvos não são enviados para servidores externos. Não há conta, anúncios nem assinatura.`, 'Perguntas frequentes', [
      { question: 'O ClipNest monitora a área de transferência o tempo todo?', answer: 'Não. Ele verifica o conteúdo atual uma vez quando o teclado é aberto.' },
      { question: 'Os textos salvos são enviados para um servidor?', answer: 'Não. Eles permanecem armazenados localmente no dispositivo.' },
      { question: 'Posso fixar textos que uso sempre?', answer: 'Sim. Itens importantes podem ser fixados para acesso rápido pelo teclado.' }
    ]),
    melivra: make('Player para biblioteca de áudio local', `Melivra é um player de música offline dedicado a coleções de áudio locais. Reproduz MP3, FLAC, WAV, ALAC, AIFF, M4A e OGG.\n\nNavegue por álbuns, artistas, compositores, gêneros e pastas, ou use a busca integrada para encontrar faixas rapidamente. Não há streaming, conta obrigatória nem feed de recomendações.\n\n## Principais recursos\n\n- Retomar reprodução, marcadores, repetição A-B e controle de velocidade\n- Playlists e letras locais\n- Visualização em lista e grade de álbuns\n- Transcrição e tradução com AI Tokens somente após aprovação explícita\n\nO Melivra Pro inclui equalizador multibanda, normalização de volume, reprodução sem intervalos e backup/restauração de playlists.`, 'Perguntas frequentes', [
      { question: 'Meus arquivos de música são enviados para um servidor?', answer: 'Na reprodução normal, não. Apenas um áudio escolhido pode ser enviado quando você aprova explicitamente uma tarefa de transcrição ou tradução por IA.' },
      { question: 'Quais formatos de áudio são suportados?', answer: 'MP3, FLAC, WAV, ALAC, AIFF, M4A e OGG.' },
      { question: 'Posso gerar transcrição e tradução?', answer: 'Sim. Após a sua aprovação, AI Tokens podem ser usados para gerar resultados exportáveis em TXT, SRT, LRC e JSON.' }
    ]),
    meriq: make('Prepare arquivos para produção de produtos', `Meriq é um espaço de trabalho móvel para preparar dados de produção de produtos personalizados.\n\nImporte a imagem de origem, escolha o tamanho do produto ou da tela e mantenha arte da frente e do verso, linha de corte, camada branca e acabamentos dentro do mesmo projeto. Confira a prévia e verificações de produção antes de exportar PNG transparente ou PDF de produção.\n\n## Principais recursos\n\n- Editar arte e camadas de produção da frente e do verso\n- Preparar linhas de corte vetoriais e camadas brancas\n- Verificações básicas de tamanho físico e resolução\n- Prévia antes da exportação\n- Exportar PNG transparente e PDF de produção\n- Desfazer e refazer durante o trabalho\n\nOs projetos e recursos importados ficam no dispositivo. Não há sincronização em nuvem por padrão e nenhum arquivo é acessado sem sua escolha.`, 'Perguntas frequentes', [
      { question: 'O Meriq envia projetos ou imagens para servidores?', answer: 'Não. Projetos, prévias e exportações são processados localmente no dispositivo.' },
      { question: 'Compras enviam o conteúdo do projeto?', answer: 'Não. App Store ou Google Play processam compras e restaurações; o conteúdo do projeto não é enviado.' },
      { question: 'Compartilhamento e exportação acontecem automaticamente?', answer: 'Não. Exportar, compartilhar ou transferir um pacote ZIP só acontece quando você inicia a ação.' }
    ]),
    quivra: make('Conversor de mídia', `Quivra é um conversor de mídia de compra única que transforma WAV, M4A, MP4 e MOV seguindo regras fixas. Não há anúncios nem assinatura.\n\nAo escolher um arquivo, o app seleciona automaticamente a conversão adequada ao formato de entrada. Você não precisa configurar o formato de saída antes de começar.\n\n## Conversões disponíveis\n\n- WAV para MP3\n- M4A para MP3\n- Extrair áudio MP3 de MP4\n- MOV para vídeo MP4\n\nO local de saída escolhido é lembrado e conflitos de nome são tratados automaticamente. O arquivo original não é alterado; um novo arquivo convertido é criado.`, 'Perguntas frequentes', [
      { question: 'Preciso escolher o formato de saída?', answer: 'Não. A conversão é escolhida automaticamente conforme o formato do arquivo de entrada.' },
      { question: 'Quais conversões são suportadas?', answer: 'WAV e M4A viram MP3, MP4 pode ter o áudio extraído para MP3 e MOV é convertido em vídeo MP4.' },
      { question: 'O arquivo original é modificado?', answer: 'Não. O original permanece intacto e o resultado é salvo como um novo arquivo.' }
    ]),
    segra: make('Cortar e combinar áudio', `Segra é uma ferramenta simples para tarefas comuns com áudio. Você pode recortar partes de MP3 e WAV, combinar várias gravações e criar um vídeo MP4 a partir de áudio e imagem.\n\nO foco não é produção musical completa, e sim recortar gravações longas, juntar arquivos na ordem escolhida e preparar vídeos simples para narração, podcasts, audiolivros ou áudio TTS.\n\n## Principais recursos\n\n- Escolher ponto inicial e final para recortar\n- Combinar vários arquivos de áudio\n- Criar MP4 com áudio e imagem\n- Preservar os arquivos originais\n- Processar tudo localmente e offline\n\nNão há login, upload de arquivos, anúncios nem rastreamento.`, 'Perguntas frequentes', [
      { question: 'O arquivo de áudio original é alterado?', answer: 'Não. Recortes e combinações são salvos como novos arquivos.' },
      { question: 'Quais tarefas de áudio são suportadas?', answer: 'Recorte de MP3/WAV, combinação de arquivos e criação de MP4 com áudio e imagem.' },
      { question: 'Os arquivos são enviados para um servidor?', answer: 'Não. O processamento ocorre no dispositivo.' }
    ]),
    tagweaver: make('Editor offline de tags MP3 e FLAC', `TagWeaver é um editor offline para conferir e editar metadados, avaliações, capas e letras em arquivos MP3 e FLAC.\n\nEdite título, artista, álbum, artista do álbum, número da faixa e do disco, ano, gênero, compositor e avaliação. Capas e letras também fazem parte do mesmo fluxo de edição.\n\n## Edição compatível\n\n- ID3 para MP3 e Vorbis Comment para FLAC\n- Campos de tags, avaliações, capas e letras\n- Seleção e edição de vários arquivos\n\nO app não reorganiza sua biblioteca automaticamente: só salva o que você conferiu e alterou. O salvamento em lote de vários arquivos faz parte do Pro. Todo o trabalho ocorre no dispositivo, sem login, upload, anúncios ou rastreamento.`, 'Perguntas frequentes', [
      { question: 'Os arquivos são enviados para um servidor?', answer: 'Não. A edição acontece localmente, sem login nem upload de arquivos.' },
      { question: 'Posso editar MP3 e FLAC?', answer: 'Sim. O TagWeaver suporta tags ID3 de MP3 e Vorbis Comment de FLAC.' },
      { question: 'Posso salvar alterações em vários arquivos de uma vez?', answer: 'Sim. Seleção e edição em lote são suportadas; o salvamento em lote de vários arquivos está disponível no Pro.' }
    ]),
    vaultxt: make('Editor para arquivos TXT grandes', `VaultXT é um editor de texto rápido e leve, projetado para arquivos grandes.\n\nAbra e edite documentos longos, logs, rascunhos e dados de texto que podem ficar pesados em apps de notas comuns. Os arquivos são abertos diretamente do dispositivo e salvos sem envio para serviços em nuvem.\n\n## Principais recursos\n\n- Abrir rapidamente arquivos TXT grandes\n- Ler e editar documentos longos\n- Salvamento automático\n- Recuperação com desfazer e snapshots\n- Armazenamento local e funcionamento offline\n\nNão há conta, anúncios nem rastreamento, e o conteúdo do arquivo não é enviado a servidores externos.`, 'Perguntas frequentes', [
      { question: 'Posso abrir arquivos TXT muito grandes?', answer: 'Sim. O VaultXT é voltado para TXT grandes, documentos longos, logs, rascunhos e dados exportados.' },
      { question: 'Como posso recuperar alterações?', answer: 'O design usa salvamento automático, desfazer e snapshots para oferecer caminhos de recuperação.' },
      { question: 'O conteúdo do arquivo é enviado para um servidor?', answer: 'Não. O processamento e o salvamento permanecem no dispositivo.' }
    ]),
    papira: make('Criador offline de EPUB a partir de TXT', `Papira transforma manuscritos TXT finalizados em livros EPUB estruturados. O app oferece fluxos próprios para fanfics, ficção seriada, romances autorais, zines digitais e cenários de TRPG, além de aceitar outros conteúdos em TXT.

## Duas formas objetivas de criar

### 1. EPUB rápido

Selecione arquivos TXT e crie EPUBs imediatamente, sem capa nem metadados de publicação.

### 2. Projeto de livro

Adicione capa, título, autor, editora, informações de série, regras de capítulos e sumário antes de exportar.

## Feito para manuscritos finalizados

- Predefinições para fanfics, ficção seriada, romances autorais, zines digitais e cenários de TRPG, com suporte a outros conteúdos TXT
- Detecção automática de capítulos, modo de títulos com # ou opção de capítulo único
- Imagem de capa, metadados do livro, informações de série, navegação e empacotamento EPUB
- Os arquivos existentes são preservados; conflitos de nome recebem numeração automática
- A criação do EPUB e o armazenamento dos projetos permanecem no dispositivo

## Seu manuscrito continua com você

- Sem conta nem login
- Sem publicidade, análise comportamental ou SDKs de rastreamento
- Manuscritos TXT e imagens de capa são processados localmente
- Projetos e EPUBs gerados não são enviados para servidores da ONNELLAB`, 'Perguntas frequentes', [
      { question: 'Os manuscritos são enviados para um servidor?', answer: 'Não. Arquivos TXT, capas, projetos, prévias e EPUBs gerados são processados no dispositivo.' },
      { question: 'Posso editar o manuscrito no Papira?', answer: 'O Papira serve para montar um manuscrito finalizado em EPUB. Faça as alterações no TXT primeiro no editor de sua preferência.' },
      { question: 'Que tipos de obra posso preparar?', answer: 'Qualquer conteúdo TXT finalizado pode ser convertido em EPUB. As predefinições apenas agilizam fluxos criativos comuns.' }
    ])
  },
  de: {
    aligna: make('Stapel-Umbenennung von Dateien', `Aligna benennt mehrere Dateien mit klaren, vorhersehbaren Regeln um.\n\nWende einheitliche Namensmuster auf Fotos, Musik und Dokumente an: Datum oder laufende Nummer ergänzen, Leerzeichen ersetzen, unzulässige Zeichen entfernen oder Musikdateinamen aus Tags erzeugen.\n\n## Hauptfunktionen\n\n- Datum oder laufende Nummern ergänzen\n- Leerzeichen durch Unterstriche ersetzen\n- Unzulässige Zeichen entfernen\n- Fotos nach Aufnahmedatum ordnen\n- Dateinamen aus Künstler, Tracknummer und Titel erzeugen\n- Änderungen vor dem Anwenden in der Vorschau prüfen\n\nAligna ist weder Dateimanager noch Cloud-Dienst. Es gibt kein Konto und keine Werbung; die Verarbeitung erfolgt auf dem Gerät. Unter iOS kann wegen Systembeschränkungen eine neu benannte Kopie gespeichert werden, statt die Originaldatei direkt umzubenennen.`, 'Häufige Fragen', [{ question: 'Wird die Originaldatei direkt umbenannt?', answer: 'Unter Android können ausgewählte Dateien umbenannt werden. Unter iOS wird wegen Systembeschränkungen eine neue Datei mit dem neuen Namen gespeichert.' }, { question: 'Kann ich die neuen Namen vorher prüfen?', answer: 'Ja. Eine Vorschau zeigt die neuen Dateinamen vor der Anwendung.' }, { question: 'Werden Dateien an einen Server gesendet?', answer: 'Nein. Die Verarbeitung erfolgt lokal auf dem Gerät.' }]),
    clipnest: make('Lokale Zwischenablage und Textbausteine', `ClipNest ist ein lokal arbeitendes Zwischenablage-Werkzeug für iPhone und iPad.\n\nBeim Öffnen der ClipNest-Tastatur wird die aktuelle Zwischenablage einmal geprüft und neuer Text auf dem Gerät gespeichert. So lassen sich Nachrichten, Adressen, E-Mail-Adressen, Links und häufige Textbausteine schnell wiederverwenden.\n\n## Hauptfunktionen\n\n- Kopierten Text beim Öffnen der Tastatur speichern\n- Direkt über die Tastatur einfügen\n- Häufige Einträge anheften\n- Letzte Kopien wiederverwenden\n- Duplikate handhaben\n- Lokale Speicherung auf dem Gerät\n\nDie Zwischenablage wird nicht dauerhaft überwacht. Gespeicherte Texte werden nicht an externe Server gesendet. Es gibt kein Konto, keine Werbung und kein Abonnement.`, 'Häufige Fragen', [{ question: 'Überwacht ClipNest die Zwischenablage ständig?', answer: 'Nein. Der aktuelle Inhalt wird einmal geprüft, wenn die Tastatur geöffnet wird.' }, { question: 'Werden gespeicherte Texte an einen Server gesendet?', answer: 'Nein. Sie bleiben lokal auf dem Gerät.' }, { question: 'Kann ich häufige Texte anheften?', answer: 'Ja. Wichtige Texte können für schnellen Zugriff über die Tastatur angeheftet werden.' }]),
    melivra: make('Player für lokale Audiosammlungen', `Melivra ist ein Offline-Musikplayer für lokale Audiosammlungen und unterstützt MP3, FLAC, WAV, ALAC, AIFF, M4A und OGG.\n\nDurchsuche deine Sammlung nach Alben, Künstlern, Komponisten, Genres und Ordnern oder finde Titel mit der integrierten Suche. Es gibt kein Streaming, kein erzwungenes Konto und keinen Empfehlungsfeed.\n\n## Hauptfunktionen\n\n- Wiedergabe fortsetzen, Lesezeichen, A-B-Wiederholung und Geschwindigkeit\n- Playlists und lokale Liedtexte\n- Listen- und Albumrasteransicht\n- KI-Transkription und -Übersetzung mit AI Tokens nur nach ausdrücklicher Zustimmung\n\nMelivra Pro bietet Mehrband-EQ, Lautstärke-Normalisierung, lückenlose Wiedergabe sowie Playlist-Backup und -Wiederherstellung.`, 'Häufige Fragen', [{ question: 'Werden Musikdateien an einen Server hochgeladen?', answer: 'Bei normaler Wiedergabe nicht. Nur wenn du einen KI-Transkriptions- oder Übersetzungsauftrag ausdrücklich bestätigst, kann die ausgewählte Audiodatei zur Verarbeitung hochgeladen werden.' }, { question: 'Welche Audioformate werden unterstützt?', answer: 'MP3, FLAC, WAV, ALAC, AIFF, M4A und OGG.' }, { question: 'Kann ich Transkriptionen und Übersetzungen erstellen?', answer: 'Ja. Nach deiner Zustimmung können AI Tokens verwendet und Ergebnisse als TXT, SRT, LRC oder JSON exportiert werden.' }]),
    meriq: make('Produktionsdateien für Merch vorbereiten', `Meriq ist ein mobiler Arbeitsbereich zur Vorbereitung von Produktionsdaten für Merch und individuelle Produkte.\n\nImportiere dein Ausgangsbild, wähle Produkt- oder Leinwandgröße und bearbeite Vorder-/Rückseite, Schnittlinie, Weißschicht und Veredelungsebenen in einem Projekt. Produktionsvorschau und Prüfungen helfen vor dem Export als transparentes PNG oder Produktions-PDF.\n\n## Hauptfunktionen\n\n- Vorder-/Rückseiten-Grafik und Produktionsebenen gemeinsam bearbeiten\n- Vektor-Schnittlinien und Weißschichten vorbereiten\n- Grundlegende Prüfungen von physischer Größe und Auflösung\n- Vorschau vor dem Export\n- Transparentes PNG und Produktions-PDF exportieren\n- Rückgängig/Wiederholen\n\nProjekte und importierte Ressourcen bleiben auf dem Gerät. Es gibt standardmäßig keine Cloud-Synchronisierung und keinen Dateizugriff ohne deine Auswahl.`, 'Häufige Fragen', [{ question: 'Lädt Meriq Projektdateien oder Bilder hoch?', answer: 'Nein. Projekte, Vorschau und Export werden lokal verarbeitet.' }, { question: 'Werden Projektinhalte bei Käufen übertragen?', answer: 'Nein. App Store oder Google Play verarbeiten Käufe und Wiederherstellungen; Projektinhalte werden nicht hochgeladen.' }, { question: 'Passiert Teilen oder Export automatisch?', answer: 'Nein. Export, Teilen und ZIP-Transfer starten nur auf deine Anweisung.' }]),
    quivra: make('Medienkonverter', `Quivra ist ein werbefreier Einmalkauf-Medienkonverter für WAV, M4A, MP4 und MOV mit festen Regeln.\n\nNach der Dateiauswahl bestimmt das Eingabeformat automatisch die passende Konvertierung. Ein Ausgabeformat muss vorher nicht gewählt werden.\n\n## Unterstützte Konvertierungen\n\n- WAV zu MP3\n- M4A zu MP3\n- MP3-Audio aus MP4 extrahieren\n- MOV zu MP4-Video\n\nDer gewählte Ausgabeordner wird gemerkt und Namenskonflikte werden automatisch behandelt. Die Originaldatei bleibt unverändert; das Ergebnis wird als neue Datei erstellt.`, 'Häufige Fragen', [{ question: 'Muss ich ein Ausgabeformat wählen?', answer: 'Nein. Die Konvertierung wird aus dem Eingabeformat abgeleitet.' }, { question: 'Welche Konvertierungen werden unterstützt?', answer: 'WAV und M4A zu MP3, MP4-Audio zu MP3 und MOV zu MP4-Video.' }, { question: 'Wird die Originaldatei verändert?', answer: 'Nein. Das Original bleibt erhalten.' }]),
    segra: make('Audio schneiden und zusammenfügen', `Segra ist ein einfaches Werkzeug für häufige Audioarbeiten. Schneide Bereiche aus MP3/WAV, füge mehrere Aufnahmen zusammen oder erstelle ein MP4-Video aus Audio und Bild.\n\nIm Mittelpunkt steht nicht Musikproduktion, sondern das Kürzen langer Aufnahmen, das Zusammenfügen in gewünschter Reihenfolge und einfache Videos für Sprechertext, Podcasts, Hörbücher oder TTS-Audio.\n\n## Hauptfunktionen\n\n- Start- und Endpunkt zum Ausschneiden wählen\n- Mehrere Audiodateien zusammenfügen\n- MP4 aus Audio und Bild erstellen\n- Originaldateien erhalten\n- Komplett lokal und offline verarbeiten\n\nKein Login, kein Datei-Upload, keine Werbung und kein Tracking.`, 'Häufige Fragen', [{ question: 'Wird die Original-Audiodatei verändert?', answer: 'Nein. Ausschnitte und Zusammenführungen werden als neue Dateien gespeichert.' }, { question: 'Welche Audioarbeiten werden unterstützt?', answer: 'MP3/WAV schneiden, Dateien zusammenfügen und MP4 aus Audio plus Bild erstellen.' }, { question: 'Werden Dateien an einen Server gesendet?', answer: 'Nein. Die Verarbeitung erfolgt auf dem Gerät.' }]),
    tagweaver: make('Offline-Editor für MP3- und FLAC-Tags', `TagWeaver ist ein Offline-Tag-Editor zum Prüfen und Bearbeiten von Metadaten, Bewertungen, Coverbildern und Liedtexten in MP3- und FLAC-Dateien.\n\nBearbeite Titel, Künstler, Album, Album-Künstler, Track- und Discnummer, Jahr, Genre, Komponist und Bewertung. Cover und Liedtexte gehören zum selben Bearbeitungsablauf.\n\n## Unterstützte Bearbeitung\n\n- MP3 ID3 und FLAC Vorbis Comment\n- Tag-Felder, Bewertung, Cover und Liedtexte\n- Mehrfachauswahl und Stapelbearbeitung\n\nDie Bibliothek wird nicht automatisch umorganisiert; gespeichert werden nur bestätigte Änderungen. Stapelspeichern für mehrere Dateien gehört zu Pro. Alles wird auf dem Gerät verarbeitet, ohne Login, Upload, Werbung oder Tracking.`, 'Häufige Fragen', [{ question: 'Werden Dateien auf einen Server hochgeladen?', answer: 'Nein. Die Bearbeitung erfolgt lokal ohne Login oder Datei-Upload.' }, { question: 'Kann ich MP3 und FLAC bearbeiten?', answer: 'Ja. Unterstützt werden MP3-ID3-Tags und FLAC-Vorbis-Comments.' }, { question: 'Kann ich mehrere Dateien gemeinsam speichern?', answer: 'Mehrfachauswahl und Stapelbearbeitung werden unterstützt; das Stapelspeichern mehrerer Dateien ist in Pro verfügbar.' }]),
    vaultxt: make('Editor für große TXT-Dateien', `VaultXT ist ein schneller, leichter Texteditor für große Dateien.\n\nÖffne und bearbeite lange Dokumente, Logs, Entwürfe und exportierte Textdaten, die in gewöhnlichen Notiz-Apps schwerfällig werden können. Dateien werden direkt vom Gerät geöffnet und ohne Cloud-Upload gespeichert.\n\n## Hauptfunktionen\n\n- Große TXT-Dateien schnell öffnen\n- Lange Dokumente lesen und bearbeiten\n- Automatisch speichern\n- Wiederherstellung mit Rückgängig und Snapshots\n- Lokal und offline arbeiten\n\nKein Konto, keine Werbung, kein Tracking; Dateiinhalte werden nicht an externe Server gesendet.`, 'Häufige Fragen', [{ question: 'Kann VaultXT sehr große TXT-Dateien öffnen?', answer: 'Ja. Es ist für große TXT-Dateien, lange Dokumente, Logs, Entwürfe und exportierte Textdaten ausgelegt.' }, { question: 'Wie kann ich Änderungen wiederherstellen?', answer: 'Automatisches Speichern, Rückgängig und Snapshots bieten Wiederherstellungsmöglichkeiten.' }, { question: 'Werden Dateiinhalte an einen Server gesendet?', answer: 'Nein. Verarbeitung und Speicherung bleiben lokal.' }]),
    papira: make('Offline-TXT-zu-EPUB-Ersteller', `Papira setzt fertige TXT-Manuskripte zu strukturierten EPUB-Büchern zusammen. Es gibt eigene Abläufe für Fanfiction, Fortsetzungsromane, eigene Romane, digitale Zines und TRPG-Szenarien; andere TXT-Inhalte lassen sich ebenfalls in EPUB umwandeln.

## Zwei gezielte Wege zum EPUB

### 1. Schnell-EPUB

Wähle TXT-Dateien aus und erstelle sofort EPUB-Dateien – ohne Cover oder Veröffentlichungsmetadaten.

### 2. Buchprojekt

Füge vor dem Export Cover, Titel, Autor, Verlag, Serieninformationen, Kapitelregeln und ein Inhaltsverzeichnis hinzu.

## Für fertige Manuskripte ausgelegt

- Voreinstellungen für Fanfiction, Fortsetzungsromane, eigene Romane, digitale Zines und TRPG-Szenarien sowie Unterstützung für andere TXT-Inhalte
- Automatische Kapitelerkennung, #-Überschriftenmodus oder Einzelkapitel-Option
- Coverbild, Buchmetadaten, Serieninformationen, Navigation und EPUB-Paketierung
- Vorhandene Dateien bleiben erhalten; bei Namenskonflikten wird automatisch eine Nummer ergänzt
- EPUB-Erstellung und Projektspeicherung bleiben auf dem Gerät

## Dein Manuskript bleibt bei dir

- Kein Konto und keine Anmeldung
- Keine Werbung, Verhaltensanalyse oder Tracking-SDKs
- TXT-Manuskripte und Coverbilder werden lokal verarbeitet
- Buchprojekte und erzeugte EPUB-Dateien werden nicht auf ONNELLAB-Server hochgeladen`, 'Häufige Fragen', [
      { question: 'Werden Manuskripte auf einen Server hochgeladen?', answer: 'Nein. TXT-Dateien, Coverbilder, Projekte, Vorschauen und erzeugte EPUB-Dateien werden auf dem Gerät verarbeitet.' },
      { question: 'Kann ich das Manuskript in Papira bearbeiten?', answer: 'Papira ist dafür gedacht, ein fertiges Manuskript als EPUB zusammenzusetzen. Bearbeite den TXT-Quelltext vorher in deinem bevorzugten Schreibprogramm.' },
      { question: 'Welche Arten von Werken kann ich vorbereiten?', answer: 'Jeder fertige TXT-Inhalt kann in EPUB umgewandelt werden. Die Voreinstellungen beschleunigen lediglich häufige kreative Abläufe.' }
    ])
  },
  fr: {
    aligna: make('Renommage de fichiers par lot', `Aligna renomme plusieurs fichiers avec des règles claires et prévisibles.\n\nAppliquez les mêmes conventions aux photos, musiques et documents : ajoutez une date ou une numérotation, remplacez les espaces, retirez les caractères interdits ou créez des noms musicaux à partir des tags.\n\n## Fonctions principales\n\n- Ajouter date ou numérotation\n- Remplacer les espaces par des tirets bas\n- Retirer les caractères interdits\n- Organiser les photos par date de prise de vue\n- Créer des noms depuis artiste, numéro de piste et titre\n- Vérifier l’aperçu avant application\n\nAligna n’est ni un explorateur de fichiers ni un service cloud. Aucun compte, aucune publicité ; le traitement reste sur l’appareil. Sur iOS, les limites du système peuvent imposer l’enregistrement d’une nouvelle copie renommée plutôt que la modification directe de l’original.`, 'Questions fréquentes', [{ question: 'Le fichier original est-il renommé directement ?', answer: 'Sur Android, les fichiers choisis peuvent être renommés. Sur iOS, une nouvelle copie portant le nouveau nom est enregistrée en raison des limites du système.' }, { question: 'Puis-je vérifier les nouveaux noms avant de les appliquer ?', answer: 'Oui. L’aperçu montre les noms obtenus avant toute modification.' }, { question: 'Les fichiers sont-ils envoyés vers un serveur ?', answer: 'Non. Le traitement reste local.' }]),
    clipnest: make('Presse-papiers local et textes réutilisables', `ClipNest est un outil de presse-papiers local pour iPhone et iPad.\n\nÀ l’ouverture du clavier ClipNest, le presse-papiers courant est vérifié une fois et les nouveaux textes sont enregistrés sur l’appareil. Messages, adresses, e-mails, liens et phrases fréquentes peuvent ainsi être réutilisés rapidement.\n\n## Fonctions principales\n\n- Enregistrer le texte copié à l’ouverture du clavier\n- Coller directement depuis le clavier\n- Épingler les éléments fréquents\n- Réutiliser l’historique récent\n- Gérer les doublons\n- Stockage local sur l’appareil\n\nLe presse-papiers n’est pas surveillé en permanence. Les textes enregistrés ne sont pas envoyés à un serveur externe. Aucun compte, aucune publicité ni abonnement.`, 'Questions fréquentes', [{ question: 'ClipNest surveille-t-il le presse-papiers en continu ?', answer: 'Non. Il vérifie le contenu actuel une seule fois lorsque le clavier s’ouvre.' }, { question: 'Les textes enregistrés sont-ils envoyés à un serveur ?', answer: 'Non. Ils restent sur l’appareil.' }, { question: 'Puis-je épingler les textes souvent utilisés ?', answer: 'Oui. Les éléments importants peuvent être épinglés pour un accès rapide.' }]),
    melivra: make('Lecteur pour bibliothèque audio locale', `Melivra est un lecteur musical hors ligne conçu pour les collections audio locales. Il lit MP3, FLAC, WAV, ALAC, AIFF, M4A et OGG.\n\nParcourez albums, artistes, compositeurs, genres et dossiers ou utilisez la recherche intégrée. Il n’y a ni streaming, ni compte imposé, ni fil de recommandations.\n\n## Fonctions principales\n\n- Reprise de lecture, signets, répétition A-B et vitesse\n- Playlists et paroles locales\n- Vue liste et grille d’albums\n- Transcription et traduction avec AI Tokens uniquement après accord explicite\n\nMelivra Pro inclut égaliseur multibande, normalisation du volume, lecture sans blanc et sauvegarde/restauration des playlists.`, 'Questions fréquentes', [{ question: 'Les fichiers audio sont-ils envoyés à un serveur ?', answer: 'Pas pour la lecture normale. Seul un fichier choisi peut être envoyé lorsque vous approuvez explicitement une transcription ou traduction IA.' }, { question: 'Quels formats sont pris en charge ?', answer: 'MP3, FLAC, WAV, ALAC, AIFF, M4A et OGG.' }, { question: 'Puis-je créer des transcriptions et traductions ?', answer: 'Oui. Après accord, des AI Tokens peuvent générer des résultats exportables en TXT, SRT, LRC ou JSON.' }]),
    meriq: make('Préparation de fichiers de production', `Meriq est un espace de travail mobile pour préparer les données de production de produits dérivés.\n\nImportez l’image source, choisissez le format du produit ou du canevas et conservez dans un même projet l’illustration recto/verso, la ligne de coupe, la couche blanche et les finitions. Vérifiez l’aperçu et les contrôles de production avant d’exporter un PNG transparent ou un PDF de production.\n\n## Fonctions principales\n\n- Modifier recto, verso et couches de production dans un même espace\n- Préparer lignes de coupe vectorielles et couches blanches\n- Contrôles de base de taille physique et résolution\n- Aperçu avant export\n- Export PNG transparent et PDF de production\n- Annuler/rétablir\n\nLes projets et ressources importées restent sur l’appareil. Pas de synchronisation cloud par défaut ni d’accès aux fichiers sans votre choix.`, 'Questions fréquentes', [{ question: 'Meriq envoie-t-il mes projets ou images à un serveur ?', answer: 'Non. Projet, aperçu et export sont traités localement.' }, { question: 'Les achats transmettent-ils le contenu du projet ?', answer: 'Non. L’App Store ou Google Play traite les achats et restaurations, pas le contenu du projet.' }, { question: 'Le partage ou l’export se fait-il automatiquement ?', answer: 'Non. Ces actions ne démarrent que lorsque vous les demandez.' }]),
    quivra: make('Convertisseur multimédia', `Quivra est un convertisseur multimédia à achat unique pour WAV, M4A, MP4 et MOV, sans publicité ni abonnement.\n\nAprès sélection d’un fichier, le format d’entrée détermine automatiquement la conversion. Aucun format de sortie n’est à configurer avant de commencer.\n\n## Conversions prises en charge\n\n- WAV vers MP3\n- M4A vers MP3\n- Extraire l’audio MP3 d’un MP4\n- MOV vers vidéo MP4\n\nLe dossier de sortie choisi est mémorisé et les conflits de nom sont gérés automatiquement. L’original reste intact et un nouveau fichier est créé.`, 'Questions fréquentes', [{ question: 'Dois-je choisir le format de sortie ?', answer: 'Non. La conversion est déterminée par le format d’entrée.' }, { question: 'Quelles conversions sont disponibles ?', answer: 'WAV/M4A vers MP3, extraction audio MP4 vers MP3 et MOV vers vidéo MP4.' }, { question: 'Le fichier original est-il modifié ?', answer: 'Non.' }]),
    segra: make('Découper et assembler de l’audio', `Segra simplifie les tâches audio courantes : découper une partie d’un MP3/WAV, assembler plusieurs enregistrements ou créer une vidéo MP4 à partir d’un audio et d’une image.\n\nL’objectif n’est pas la production musicale complète, mais le découpage d’enregistrements longs, l’assemblage dans l’ordre choisi et les vidéos simples pour narration, podcasts, livres audio ou TTS.\n\n## Fonctions principales\n\n- Choisir début et fin d’un extrait\n- Assembler plusieurs fichiers audio\n- Créer un MP4 avec audio et image\n- Préserver les fichiers originaux\n- Tout traiter localement et hors ligne\n\nAucune connexion, aucun envoi de fichier, aucune publicité ni suivi.`, 'Questions fréquentes', [{ question: 'Le fichier audio original est-il modifié ?', answer: 'Non. Les extraits et assemblages sont enregistrés comme nouveaux fichiers.' }, { question: 'Quelles tâches audio sont prises en charge ?', answer: 'Découpe MP3/WAV, assemblage de fichiers et création MP4 avec audio et image.' }, { question: 'Les fichiers sont-ils envoyés à un serveur ?', answer: 'Non.' }]),
    tagweaver: make('Éditeur hors ligne de tags MP3/FLAC', `TagWeaver permet de vérifier et modifier hors ligne métadonnées, notes, pochettes et paroles des fichiers MP3 et FLAC.\n\nModifiez titre, artiste, album, artiste de l’album, numéros de piste et de disque, année, genre, compositeur et note. Pochettes et paroles sont gérées dans le même flux.\n\n## Modifications prises en charge\n\n- ID3 pour MP3 et Vorbis Comment pour FLAC\n- Champs de tags, notes, pochettes et paroles\n- Sélection et édition de plusieurs fichiers\n\nLa bibliothèque n’est pas réorganisée automatiquement : seules les modifications vérifiées sont enregistrées. L’enregistrement en lot de plusieurs fichiers est disponible avec Pro. Tout reste sur l’appareil, sans connexion, envoi, publicité ni suivi.`, 'Questions fréquentes', [{ question: 'Les fichiers sont-ils envoyés à un serveur ?', answer: 'Non. La modification est locale.' }, { question: 'Puis-je modifier MP3 et FLAC ?', answer: 'Oui. ID3 MP3 et Vorbis Comment FLAC sont pris en charge.' }, { question: 'Puis-je enregistrer plusieurs fichiers ensemble ?', answer: 'Oui. La sélection et l’édition en lot sont prises en charge ; l’enregistrement multiple est disponible avec Pro.' }]),
    vaultxt: make('Éditeur de gros fichiers TXT', `VaultXT est un éditeur de texte rapide et léger conçu pour les gros fichiers.\n\nOuvrez et modifiez longs documents, journaux, brouillons et données texte exportées sans les envoyer vers un service cloud.\n\n## Fonctions principales\n\n- Ouvrir rapidement de gros TXT\n- Lire et modifier de longs documents\n- Sauvegarde automatique\n- Récupération avec annulation et snapshots\n- Travail local et hors ligne\n\nAucun compte, aucune publicité ni suivi ; le contenu n’est pas envoyé à un serveur externe.`, 'Questions fréquentes', [{ question: 'Puis-je ouvrir de très gros fichiers TXT ?', answer: 'Oui. VaultXT est conçu pour les gros TXT, longs documents, logs, brouillons et données exportées.' }, { question: 'Comment récupérer mes modifications ?', answer: 'Sauvegarde automatique, annulation et snapshots offrent des voies de récupération.' }, { question: 'Le contenu est-il envoyé à un serveur ?', answer: 'Non.' }]),
    papira: make('Créateur EPUB hors ligne à partir de TXT', `Papira assemble des manuscrits TXT finalisés en livres EPUB structurés. L’application propose des parcours dédiés aux fanfictions, romans-feuilletons, romans personnels, zines numériques et scénarios de JDR sur table, tout en acceptant d’autres contenus TXT.

## Deux façons ciblées de créer

### 1. EPUB rapide

Sélectionnez des fichiers TXT et créez immédiatement des EPUB, sans couverture ni métadonnées de publication.

### 2. Projet de livre

Ajoutez une couverture, un titre, un auteur, un éditeur, des informations de série, des règles de chapitrage et une table des matières avant l’exportation.

## Pensé pour les manuscrits finalisés

- Préréglages pour fanfictions, romans-feuilletons, romans personnels, zines numériques et scénarios de JDR sur table, avec prise en charge d’autres contenus TXT
- Détection automatique des chapitres, mode de titres avec # ou option de chapitre unique
- Image de couverture, métadonnées du livre, informations de série, navigation et empaquetage EPUB
- Les fichiers existants sont conservés ; un numéro est ajouté automatiquement en cas de conflit de nom
- La création des EPUB et le stockage des projets restent sur l’appareil

## Votre manuscrit reste avec vous

- Aucun compte ni connexion
- Aucune publicité, analyse comportementale ou SDK de suivi
- Les manuscrits TXT et images de couverture sont traités localement
- Les projets et EPUB générés ne sont pas envoyés vers un serveur ONNELLAB`, 'Questions fréquentes', [
      { question: 'Les manuscrits sont-ils envoyés vers un serveur ?', answer: 'Non. Les fichiers TXT, couvertures, projets, aperçus et EPUB générés sont traités sur l’appareil.' },
      { question: 'Puis-je modifier le manuscrit dans Papira ?', answer: 'Papira sert à assembler un manuscrit finalisé en EPUB. Modifiez d’abord le TXT source dans votre outil d’écriture habituel.' },
      { question: 'Quels types d’œuvres puis-je préparer ?', answer: 'Tout contenu TXT finalisé peut être converti en EPUB. Les préréglages servent seulement à accélérer les flux créatifs courants.' }
    ])
  },
  es: {
    aligna: make('Renombrador de archivos por lotes', `Aligna cambia el nombre de varios archivos usando reglas claras y predecibles.\n\nAplica patrones uniformes a fotos, música y documentos: añade fechas o números correlativos, cambia espacios por guiones bajos, elimina caracteres no válidos y genera nombres musicales a partir de etiquetas.\n\n## Funciones principales\n\n- Añadir fecha o numeración\n- Sustituir espacios por guiones bajos\n- Eliminar caracteres no válidos\n- Organizar fotos por fecha de captura\n- Crear nombres con artista, número de pista y título\n- Revisar una vista previa antes de aplicar\n\nAligna no es un explorador de archivos ni un servicio en la nube. No requiere cuenta, no tiene anuncios y procesa todo en el dispositivo. En iOS, las restricciones del sistema pueden hacer que se guarde una copia con el nuevo nombre en vez de renombrar directamente el original.`, 'Preguntas frecuentes', [{ question: '¿Se cambia directamente el nombre del archivo original?', answer: 'En Android se pueden renombrar los archivos seleccionados. En iOS se guarda una nueva copia con el nombre nuevo debido a las restricciones del sistema.' }, { question: '¿Puedo revisar los nombres antes de aplicarlos?', answer: 'Sí. La vista previa muestra el resultado antes de modificar nada.' }, { question: '¿Se envían archivos a un servidor?', answer: 'No. El procesamiento es local.' }]),
    clipnest: make('Portapapeles local y textos reutilizables', `ClipNest es una herramienta local de portapapeles para iPhone y iPad.\n\nAl abrir el teclado de ClipNest se revisa una vez el contenido actual del portapapeles y se guarda el texto nuevo en el dispositivo. Así puedes reutilizar mensajes, direcciones, correos, enlaces y frases frecuentes sin volver a buscarlos.\n\n## Funciones principales\n\n- Guardar texto copiado al abrir el teclado\n- Pegar directamente desde el teclado\n- Fijar elementos frecuentes\n- Reutilizar el historial reciente\n- Gestionar duplicados\n- Almacenamiento local\n\nClipNest no vigila el portapapeles continuamente. Los textos guardados no se envían a servidores externos. No hay cuenta, anuncios ni suscripción.`, 'Preguntas frecuentes', [{ question: '¿ClipNest vigila el portapapeles todo el tiempo?', answer: 'No. Comprueba el contenido actual una sola vez al abrir el teclado.' }, { question: '¿Los textos guardados se envían a un servidor?', answer: 'No. Permanecen en el dispositivo.' }, { question: '¿Puedo fijar textos de uso frecuente?', answer: 'Sí. Puedes fijarlos para acceder rápidamente desde el teclado.' }]),
    melivra: make('Reproductor para biblioteca de audio local', `Melivra es un reproductor de música sin conexión pensado para colecciones locales. Reproduce MP3, FLAC, WAV, ALAC, AIFF, M4A y OGG.\n\nExplora por álbumes, artistas, compositores, géneros y carpetas o usa la búsqueda integrada. No hay streaming, cuenta obligatoria ni feed de recomendaciones.\n\n## Funciones principales\n\n- Reanudar reproducción, marcadores, repetición A-B y velocidad\n- Listas de reproducción y letras locales\n- Vista de lista y cuadrícula de álbumes\n- Transcripción y traducción con AI Tokens solo tras aprobación explícita\n\nMelivra Pro incluye ecualizador multibanda, normalización de volumen, reproducción sin pausas y copia/restauración de listas.`, 'Preguntas frecuentes', [{ question: '¿Se suben mis archivos de música a un servidor?', answer: 'Durante la reproducción normal, no. Solo puede subirse el audio elegido si apruebas expresamente una tarea de transcripción o traducción con IA.' }, { question: '¿Qué formatos se reproducen?', answer: 'MP3, FLAC, WAV, ALAC, AIFF, M4A y OGG.' }, { question: '¿Puedo generar transcripciones y traducciones?', answer: 'Sí. Tras aprobarlo, AI Tokens pueden generar resultados exportables en TXT, SRT, LRC y JSON.' }]),
    meriq: make('Preparación de archivos de producción', `Meriq es un espacio de trabajo móvil para preparar datos de producción de merchandising y productos personalizados.\n\nImporta la imagen de origen, elige el tamaño del producto o lienzo y reúne en un proyecto ilustración frontal/trasera, línea de corte, capa blanca y acabados. Revisa la previsualización y las comprobaciones antes de exportar PNG transparente o PDF de producción.\n\n## Funciones principales\n\n- Editar arte frontal/trasero y capas de producción\n- Preparar líneas de corte vectoriales y capas blancas\n- Comprobar tamaño físico y resolución\n- Previsualizar antes de exportar\n- Exportar PNG transparente y PDF de producción\n- Deshacer y rehacer\n\nLos proyectos y recursos importados permanecen en el dispositivo. No hay sincronización en la nube por defecto ni acceso a archivos que no elijas.`, 'Preguntas frecuentes', [{ question: '¿Meriq sube proyectos o imágenes?', answer: 'No. Proyecto, previsualización y exportación se procesan localmente.' }, { question: '¿Las compras envían el contenido del proyecto?', answer: 'No. App Store o Google Play procesan compras y restauraciones, no el contenido.' }, { question: '¿Compartir o exportar ocurre automáticamente?', answer: 'No. Solo empieza cuando tú lo inicias.' }]),
    quivra: make('Conversor multimedia', `Quivra es un conversor multimedia de pago único para WAV, M4A, MP4 y MOV. No tiene anuncios ni suscripción.\n\nAl elegir un archivo, el formato de entrada determina automáticamente la conversión. No necesitas configurar el formato de salida.\n\n## Conversiones compatibles\n\n- WAV a MP3\n- M4A a MP3\n- Extraer audio MP3 de MP4\n- MOV a vídeo MP4\n\nSe recuerda la ubicación de salida y los conflictos de nombre se gestionan automáticamente. El original no se modifica; se crea un archivo nuevo.`, 'Preguntas frecuentes', [{ question: '¿Tengo que elegir el formato de salida?', answer: 'No. Se determina según el formato de entrada.' }, { question: '¿Qué conversiones admite?', answer: 'WAV/M4A a MP3, extracción de audio MP4 a MP3 y MOV a vídeo MP4.' }, { question: '¿Se modifica el original?', answer: 'No.' }]),
    segra: make('Cortar y unir audio', `Segra simplifica tareas comunes de audio: recortar una parte de MP3/WAV, unir varias grabaciones o crear un vídeo MP4 con audio e imagen.\n\nNo pretende ser una suite de producción musical. Se centra en recortar grabaciones largas, unir archivos en el orden elegido y preparar vídeos sencillos para narración, podcasts, audiolibros o TTS.\n\n## Funciones principales\n\n- Elegir inicio y final del recorte\n- Unir varios archivos de audio\n- Crear MP4 con audio e imagen\n- Conservar originales\n- Procesar todo localmente y sin conexión\n\nNo hay inicio de sesión, subida de archivos, anuncios ni seguimiento.`, 'Preguntas frecuentes', [{ question: '¿Se modifica el audio original?', answer: 'No. Los recortes y uniones se guardan como archivos nuevos.' }, { question: '¿Qué tareas admite?', answer: 'Recorte de MP3/WAV, unión de archivos y creación de MP4 con audio e imagen.' }, { question: '¿Se envían los archivos a un servidor?', answer: 'No.' }]),
    tagweaver: make('Editor sin conexión de etiquetas MP3/FLAC', `TagWeaver permite revisar y editar sin conexión metadatos, puntuaciones, carátulas y letras en archivos MP3 y FLAC.\n\nEdita título, artista, álbum, artista del álbum, números de pista y disco, año, género, compositor y puntuación. Las carátulas y letras se gestionan en el mismo flujo.\n\n## Edición compatible\n\n- ID3 de MP3 y Vorbis Comment de FLAC\n- Campos, puntuaciones, carátulas y letras\n- Selección y edición de varios archivos\n\nLa biblioteca no se reorganiza automáticamente: solo se guardan los cambios que revisas. El guardado por lotes de varios archivos está disponible con Pro. Todo ocurre en el dispositivo, sin login, subidas, anuncios ni seguimiento.`, 'Preguntas frecuentes', [{ question: '¿Se suben los archivos a un servidor?', answer: 'No. La edición es local.' }, { question: '¿Puedo editar MP3 y FLAC?', answer: 'Sí. Se admiten ID3 de MP3 y Vorbis Comment de FLAC.' }, { question: '¿Puedo guardar varios archivos a la vez?', answer: 'Sí. Hay selección y edición por lotes; el guardado múltiple forma parte de Pro.' }]),
    vaultxt: make('Editor de archivos TXT grandes', `VaultXT es un editor de texto rápido y ligero diseñado para archivos grandes.\n\nAbre y edita documentos largos, registros, borradores y datos exportados sin enviarlos a servicios en la nube.\n\n## Funciones principales\n\n- Abrir rápidamente TXT grandes\n- Leer y editar documentos largos\n- Guardado automático\n- Recuperación con deshacer y snapshots\n- Trabajo local y sin conexión\n\nNo hay cuenta, anuncios ni seguimiento; el contenido no se envía a servidores externos.`, 'Preguntas frecuentes', [{ question: '¿Puedo abrir archivos TXT muy grandes?', answer: 'Sí. VaultXT está diseñado para TXT grandes, documentos largos, logs, borradores y datos exportados.' }, { question: '¿Cómo puedo recuperar cambios?', answer: 'Guardado automático, deshacer y snapshots ofrecen opciones de recuperación.' }, { question: '¿Se envía el contenido a un servidor?', answer: 'No.' }]),
    papira: make('Creador de EPUB sin conexión a partir de TXT', `Papira convierte manuscritos TXT terminados en libros EPUB estructurados. Incluye flujos específicos para fanfiction, ficción por entregas, novelas personales, zines digitales y escenarios de TRPG, y también admite otros contenidos TXT.

## Dos formas directas de crear

### 1. EPUB rápido

Selecciona archivos TXT y crea EPUB de inmediato, sin portada ni metadatos de publicación.

### 2. Proyecto de libro

Añade portada, título, autor, editorial, información de serie, reglas de capítulos y tabla de contenidos antes de exportar.

## Pensado para manuscritos terminados

- Ajustes para fanfiction, ficción por entregas, novelas personales, zines digitales y escenarios de TRPG, además de otros contenidos TXT
- Detección automática de capítulos, modo de encabezados con # u opción de capítulo único
- Imagen de portada, metadatos del libro, información de serie, navegación y empaquetado EPUB
- Los archivos existentes se conservan; si hay conflicto de nombres se añade un número automáticamente
- La creación del EPUB y el almacenamiento de proyectos permanecen en el dispositivo

## Tu manuscrito se queda contigo

- Sin cuenta ni inicio de sesión
- Sin publicidad, analítica de comportamiento ni SDK de seguimiento
- Los manuscritos TXT y las imágenes de portada se procesan localmente
- Los proyectos y EPUB generados no se suben a servidores de ONNELLAB`, 'Preguntas frecuentes', [
      { question: '¿Los manuscritos se suben a un servidor?', answer: 'No. Los archivos TXT, portadas, proyectos, vistas previas y EPUB generados se procesan en el dispositivo.' },
      { question: '¿Puedo editar el manuscrito en Papira?', answer: 'Papira está pensado para montar un manuscrito terminado como EPUB. Edita primero el TXT original en tu herramienta de escritura habitual.' },
      { question: '¿Qué tipos de obras puedo preparar?', answer: 'Cualquier contenido TXT terminado puede convertirse en EPUB. Los ajustes específicos solo agilizan flujos creativos habituales.' }
    ])
  }
};

export function getExtendedProductCopy(slug: string, locale: ExtendedSiteLocale): ExtendedProductCopy {
  const copy = extendedProductCopy[locale][slug];
  if (!copy) throw new Error(`Missing extended product localization: ${locale}/${slug}`);
  return copy;
}
