import type { AllSiteLocale } from './extended-site-i18n';

/** Web introduction, feature list and privacy note. Store copy is maintained separately. */
export const papiraDescription: Record<AllSiteLocale, string> = {
  "en": "Papira assembles any finished TXT manuscript into a well-structured EPUB. It includes dedicated flows for fanfiction, serialized fiction, original novels, digital zines, and TRPG scenarios, while other TXT content can also be converted to EPUB.\n\n## Key features\n\n- Create an EPUB directly from TXT with Quick EPUB, without a cover or publishing metadata\n- Build a book project with a cover, title, author, publisher and series details\n- Detect chapters automatically, use # headings or keep a single chapter\n- Build navigation and a table of contents, and review book details before export\n- Use presets for fanfiction, serialized fiction, original novels, digital zines and TRPG scenarios, or convert other finished TXT content\n- Preserve existing files by adding a number when an output name is already in use\n- Create EPUB files and store book projects on your device\n\nThere is no account, sign-in, advertising, behavioral analytics, or tracking SDK. TXT manuscripts, cover images, projects, previews, and generated EPUB files are processed locally and are not uploaded to an ONNELLAB server.",
  "ko": "Papira는 완성된 TXT 원고를 정돈된 책 파일(EPUB)로 만들어요. 팬픽·연재소설·개인 창작 소설·디지털 소책자·TRPG 시나리오에 특화된 제작 흐름을 제공하지만, 그 밖의 TXT 콘텐츠도 EPUB으로 변환할 수 있어요.\n\n## 주요 기능\n\n- 빠르게 만들기로 표지·출판 정보 없이 TXT를 EPUB으로 변환\n- 책 프로젝트에서 표지·제목·저자·출판사·시리즈 정보 구성\n- 자동 감지·# 제목 모드·단일 챕터 중 챕터 구성 방식 선택\n- 챕터 이동과 목차 구성, 내보내기 전 책 정보 확인\n- 팬픽·연재소설·창작 소설·소책자·TRPG 시나리오 특화 유형과 그 밖의 TXT 지원\n- 파일 이름이 겹치면 번호를 붙여 기존 파일 보존\n- 기기 안에서 EPUB 제작과 책 프로젝트 저장\n\n계정이나 로그인이 필요 없고, 광고·행동 분석·추적 SDK를 사용하지 않아요. TXT 원고, 표지 이미지, 책 프로젝트, 미리보기와 생성한 EPUB은 기기 안에서 처리하며 ONNELLAB 서버에 업로드하지 않아요.",
  "ja": "Papiraは完成したTXT原稿を整ったEPUBにまとめます。二次創作・連載小説・オリジナル小説・デジタル小冊子・TRPGシナリオに特化した作成フローを備えていますが、そのほかのTXTコンテンツもEPUBに変換できます。\n\n## 主な機能\n\n- 「すぐにEPUB化」で、表紙や書誌情報なしにTXTからEPUBを作成\n- 書籍プロジェクトで表紙・タイトル・著者・出版社・シリーズ情報を設定\n- 章の自動検出・「#」見出しモード・単一章から構成方法を選択\n- ナビゲーションと目次を作成し、書き出し前に書誌情報を確認\n- 二次創作・連載小説・オリジナル小説・デジタル小冊子・TRPGシナリオ向けのプリセットと、そのほかのTXTに対応\n- 同名ファイルがあるときは番号を付けて既存ファイルを保持\n- EPUB作成と書籍プロジェクトの保存を端末内で実行\n\nアカウントやログインは不要で、広告、行動分析、トラッキングSDKも使用しません。TXT原稿、表紙画像、プロジェクト、プレビュー、作成したEPUBは端末内で処理され、ONNELLABのサーバーにはアップロードされません。",
  "zh-Hans": "Papira 可将完成的 TXT 文稿整理成结构清晰的 EPUB。它特别适合同人文、连载小说、原创小说、数字小册子与 TRPG 剧本，也能将其他 TXT 内容转换为 EPUB。\n\n## 主要功能\n\n- 通过“快速 EPUB”直接将 TXT 转为 EPUB，无需封面或出版信息\n- 在书籍项目中设置封面、标题、作者、出版方和系列信息\n- 选择自动章节检测、# 标题模式或单一章节\n- 建立导航与目录，并在导出前检查书籍信息\n- 使用同人文、连载小说、原创小说、数字小册子及 TRPG 剧本预设，也支持其他完成的 TXT 内容\n- 输出文件名重复时自动添加编号，保留已有文件\n- 在设备上创建 EPUB 并保存书籍项目\n\n无需账户或登录，也没有广告、行为分析或跟踪 SDK。TXT 稿件、封面图片、项目、预览和生成的 EPUB 都在设备本地处理，不会上传到 ONNELLAB 服务器。",
  "zh-Hant": "Papira 可將完成的 TXT 文稿整理成結構清楚的 EPUB。它特別適合同人文、連載小說、原創小說、數位小冊子與 TRPG 劇本，也能將其他 TXT 內容轉換為 EPUB。\n\n## 主要功能\n\n- 透過「快速 EPUB」直接將 TXT 轉為 EPUB，不必設定封面或出版資訊\n- 在書籍專案中設定封面、標題、作者、出版者與系列資訊\n- 選擇自動章節偵測、# 標題模式或單一章節\n- 建立導覽與目錄，並在匯出前確認書籍資訊\n- 使用同人文、連載小說、原創小說、數位小冊子與 TRPG 劇本預設，也支援其他完成的 TXT 內容\n- 輸出檔名重複時自動加上編號，保留現有檔案\n- 在裝置上建立 EPUB 並儲存書籍專案\n\n不需要帳戶或登入，也沒有廣告、行為分析或追蹤 SDK。TXT 稿件、封面圖片、專案、預覽和產生的 EPUB 都在裝置本機處理，不會上傳到 ONNELLAB 伺服器。",
  "pt-BR": "Papira transforma manuscritos TXT finalizados em livros EPUB estruturados. O app oferece fluxos próprios para fanfics, ficção seriada, romances autorais, zines digitais e cenários de TRPG, além de aceitar outros conteúdos em TXT.\n\n## Principais recursos\n\n- Criar EPUB diretamente de TXT no EPUB rápido, sem capa nem metadados de publicação\n- Montar um projeto de livro com capa, título, autor, editora e informações de série\n- Detectar capítulos automaticamente, usar títulos com # ou manter um capítulo único\n- Criar navegação e sumário e conferir os dados do livro antes de exportar\n- Usar predefinições para fanfics, ficção seriada, romances autorais, zines digitais e cenários de TRPG, ou converter outros textos TXT finalizados\n- Preservar arquivos existentes, acrescentando um número quando o nome de saída já estiver em uso\n- Criar EPUBs e guardar projetos de livro no dispositivo\n\nNão há conta nem login, publicidade, análise comportamental ou SDK de rastreamento. Manuscritos TXT, imagens de capa, projetos, prévias e EPUBs gerados são processados localmente e não são enviados para servidores da ONNELLAB.",
  "de": "Papira setzt fertige TXT-Manuskripte zu strukturierten EPUB-Büchern zusammen. Es gibt eigene Abläufe für Fanfiction, Fortsetzungsromane, eigene Romane, digitale Zines und TRPG-Szenarien; andere TXT-Inhalte lassen sich ebenfalls in EPUB umwandeln.\n\n## Hauptfunktionen\n\n- Mit Schnell-EPUB TXT direkt in EPUB umwandeln, ohne Cover oder Veröffentlichungsmetadaten\n- Buchprojekte mit Cover, Titel, Autor, Verlag und Serieninformationen vorbereiten\n- Kapitel automatisch erkennen, über #-Überschriften gliedern oder als ein Kapitel anlegen\n- Navigation und Inhaltsverzeichnis erstellen und Buchdaten vor dem Export prüfen\n- Vorlagen für Fanfiction, Fortsetzungsromane, eigene Romane, digitale Zines und TRPG-Szenarien nutzen oder andere fertige TXT-Inhalte umwandeln\n- Vorhandene Dateien erhalten und bei Namenskonflikten automatisch eine Nummer ergänzen\n- EPUB-Dateien und Buchprojekte auf dem Gerät erstellen und speichern\n\nEs gibt kein Konto und keine Anmeldung, keine Werbung, Verhaltensanalyse oder Tracking-SDKs. TXT-Manuskripte, Coverbilder, Projekte, Vorschauen und erzeugte EPUB-Dateien werden lokal verarbeitet und nicht auf einen ONNELLAB-Server hochgeladen.",
  "fr": "Papira assemble des manuscrits TXT finalisés en livres EPUB structurés. L’application propose des parcours dédiés aux fanfictions, romans-feuilletons, romans originaux, zines numériques et scénarios de JDR sur table, tout en acceptant d’autres contenus TXT.\n\n## Fonctions principales\n\n- Créer directement un EPUB depuis un TXT avec l’EPUB rapide, sans couverture ni métadonnées de publication\n- Préparer un projet de livre avec couverture, titre, auteur, éditeur et informations de série\n- Détecter les chapitres automatiquement, utiliser les titres commençant par # ou conserver un seul chapitre\n- Créer la navigation et la table des matières, puis vérifier les informations du livre avant l’exportation\n- Utiliser des préréglages pour fanfictions, romans-feuilletons, romans originaux, zines numériques et scénarios de JDR sur table, ou convertir d’autres textes TXT finalisés\n- Conserver les fichiers existants en ajoutant un numéro lorsque le nom de sortie est déjà utilisé\n- Créer les EPUB et stocker les projets de livre sur l’appareil\n\nAucun compte ni connexion n’est requis, et l’application n’utilise ni publicité, ni analyse comportementale, ni SDK de suivi. Manuscrits TXT, images de couverture, projets, aperçus et EPUB générés sont traités localement et ne sont pas envoyés vers un serveur ONNELLAB.",
  "es": "Papira convierte manuscritos TXT terminados en libros EPUB estructurados. Incluye flujos específicos para fanfiction, ficción por entregas, novelas originales, zines digitales y escenarios de TRPG, y también admite otros contenidos TXT.\n\n## Funciones principales\n\n- Crear EPUB directamente desde TXT con EPUB rápido, sin portada ni metadatos de publicación\n- Preparar un proyecto de libro con portada, título, autor, editorial e información de serie\n- Detectar capítulos automáticamente, usar encabezados con # o mantener un solo capítulo\n- Crear la navegación y la tabla de contenidos y revisar los datos antes de exportar\n- Usar ajustes para fanfiction, ficción por entregas, novelas originales, zines digitales y escenarios de TRPG, o convertir otros textos TXT terminados\n- Conservar los archivos existentes añadiendo un número cuando el nombre de salida ya esté en uso\n- Crear EPUB y guardar proyectos de libro en el dispositivo\n\nNo necesitas cuenta ni iniciar sesión, y no hay publicidad, analítica de comportamiento ni SDK de seguimiento. Los manuscritos TXT, las imágenes de portada, los proyectos, las vistas previas y los EPUB generados se procesan localmente y no se suben a servidores de ONNELLAB."
};

export function getPapiraDescription(locale: AllSiteLocale): string {
  return papiraDescription[locale];
}

/** Search summary reviewed with the web body; not copied from legacy store prose. */
export const papiraSeoDescriptions: Record<AllSiteLocale, string> = {
  "en": "Turn finished TXT manuscripts into EPUB books with Papira. Add a cover, book details, chapters and a table of contents, entirely on your device.",
  "ko": "Papira로 완성된 TXT 원고를 EPUB 전자책으로 만들어요. 표지, 책 정보, 챕터와 목차를 구성하고 기기 안에서 내보내요. 원고를 서버에 업로드하지 않아요.",
  "ja": "Papiraで完成したTXT原稿をEPUBに。表紙・書誌情報・章・目次を整え、端末内で書き出せます。原稿をサーバーにアップロードする必要はありません。",
  "zh-Hans": "用 Papira 将完成的 TXT 文稿制作成 EPUB 电子书。设置封面、书籍信息、章节和目录，在设备上导出，无需将稿件上传到服务器。",
  "zh-Hant": "用 Papira 將完成的 TXT 文稿製作成 EPUB 電子書。設定封面、書籍資訊、章節與目錄，在裝置上匯出，不必將稿件上傳到伺服器。",
  "pt-BR": "Transforme manuscritos TXT em livros EPUB com Papira. Adicione capa, dados do livro, capítulos e sumário. Todo o processo acontece no seu dispositivo.",
  "de": "Mit Papira fertige TXT-Manuskripte in EPUB-Bücher umwandeln. Cover, Buchdaten, Kapitel und Inhaltsverzeichnis ergänzen – alles lokal auf deinem Gerät.",
  "fr": "Créez des livres EPUB à partir de manuscrits TXT avec Papira. Ajoutez couverture, informations du livre, chapitres et table des matières, sans envoi au serveur.",
  "es": "Crea libros EPUB a partir de manuscritos TXT con Papira. Añade portada, datos del libro, capítulos e índice. Todo se procesa en tu dispositivo."
};

export function getPapiraSeoDescription(locale: AllSiteLocale): string {
  return papiraSeoDescriptions[locale];
}
